### DISCUSSION TITLE
Reload fluentX certificates when the TLS secrets changes

### DISCUSSION THREAD

**Discussion by aslafy-z** [kube-logging/logging-operator#1308] [General]
**Is your feature request related to a problem? Please describe.**
I generate certificates for fluentbit and fluentd using cert-manager. When they are renewed, logging-operator does not rollout the resources. I found that fluentbit was not re-loading the TLS certificates by itself when the file mounted from the secret is updated (see https://github.com/fluent/fluent-bit/issues/1678). Not sure about fluentd. 

**Describe the solution you'd like**
Logging operator watches the secrets and start a rollout when it changes.

**Describe alternatives you've considered**
Use stackater/reloader to do so, but I think it's a bit hackish. Logging operator should manage the sts/ds by itself.

**Comment by aslafy-z** [comment]
I tried to use Reloader to start the rollouts, but it appears that there is no statefulsetAnnotations / daemonsetAnnotations field, which prevents the use of it.

```yaml
# LoggingSpec
fluentbit:
  annotations:
    secret.reloader.stakater.com/reload: "tls-fluentbit"
fluentd:
  annotations:
    secret.reloader.stakater.com/reload: "tls-fluentd"
```

this adds annotations the statefulset / daemonset pod template, not in its own metadata.
