### DISCUSSION TITLE
Ability to remove fields/groups of fields for the Kubernetes labels and annotations

### DISCUSSION THREAD

**Discussion by silverm0on** [kube-logging/logging-operator#1371] [Q&A]
I would like the ability to remove some  annotations and labels in the kubernetes fields.
I use [record_modifier](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/record_modifier/) but it's not working for kubernetes fields

**Comment by liquidsaul** [comment]
Bump on this, did you find a solution @silverm0on ?

**Comment by silverm0on** [comment]
@liquidsaul  Nope just disable all  kubernetes labels  in logging resource

    filterKubernetes:
      Labels: "Off"

**Comment by duhow** [comment]
I'm also interested on this. I've tested using `remove_keys` in both Flow and Output without success.

I want to remove unneeded Kubernetes `labels` to avoid sending to Loki.

**Comment by SSvilen** [comment]
@duhow 

you can do something like this in the output and pick only the labels you want:
```yaml
    configure_kubernetes_labels: false
    labels:
      namespace: "$.kubernetes.namespace_name"
      pod: "$.kubernetes.pod_name"
      container: "$.kubernetes.container_name"
      host: "$.kubernetes.host"
```
