### DISCUSSION TITLE
ServiceAccount annotation is only added to logging-operator serviceaccount

### DISCUSSION THREAD

**Discussion by WTPascoe** [kube-logging/logging-operator#1376] [Q&A]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
When deploying the logging operator with a service account annotation to use an EKS role (IRSA), the annotation is only created on the logging-operator service account during `helm install` and not on subsequent accounts created when creating logging resources.

I _think_ this may be a documentation issue, and that I simply need to include config in the following section of the logging resource, but I couldn't find documentation on whether that is the case or not.

```
spec:
  fluentd: {}
  fluentbit: {}
```

**Expected behaviour**:
all of the following service accounts should have the IRSA annotation applied:

* logging-fluentbit
* logging-fluentd
* logging-operator

**Steps to reproduce the bug**:
`helm upgrade --install --version 3.17.9 --wait --values values.yml --namespace logging logging-operator banzaicloud-stable/logging-operator`

_values.yml contents_
```
createCustomResource: false
serviceAccount:
  annotations: 
    eks.amazonaws.com/role-arn: "arn:aws:iam::myacc:role/myrole"
```

_Check annotation_
```
$ k get sa logging-operator -o yaml| grep -A3 annotation
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::myacc:role/myrole
    meta.helm.sh/release-name: logging-operator
    meta.helm.sh/release-namespace: logging
```

_Create logging resource_
```
$ kubectl -n logging apply -f - <<EOF
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging
EOF
```

_Newly created service account does not have annotation_
```
$ k get sa logging-fluentd -o yaml | gre
p -A3 annotation
  annotations:
    banzaicloud.com/last-applied: <removed>
  creationTimestamp: "2022-10-18T11:03:01Z"
  labels:
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.23
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS EKS
- logging-operator version (e.g. 2.1.1): 3.17.9
- Install method (e.g. helm or static manifests): helm
- 
/kind bug

**Comment by yurrriq** [comment]
I couldn't find solid documentation either, but you can do the following in a Logging resource:

```yaml
spec:
  fluentd:
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::myacc:role/myrole"
```
