### DISCUSSION TITLE
nodeAgents deprecated - how to enable windows support?

### DISCUSSION THREAD

**Discussion by mweibel** [kube-logging/logging-operator#1650] [Q&A] [answered]
We're using logging-operator since >3 years and finally are upgrading to the latest and greatest version. 
Since we unfortunately need windows nodes in our cluster, we also need windows support. 

So far we've enabled it by setting `nodeAgents` in the `Logging` CRD as follows:
```
nodeAgents:
  - name: winagent
    profile: windows
    nodeAgentFluentbit:
      tls:
        enabled: false
      inputTail:
        Buffer_Chunk_Size: "1MB"
        Buffer_Max_Size: "5MB"
      daemonSet:
        spec:
          template:
            spec:
              nodeSelector:
                kubernetes.io/os: windows
              tolerations:
                - operator: Exists
              containers:
                - name: fluent-bit
                  image: fluent/fluent-bit:windows-2019-2.2.2
                  resources:
                    limits:
                      cpu: 500m
                      memory: 500M
                    requests:
                      cpu: 200m
                      memory: 200M
```

I've seen in the [CRD docs](https://kube-logging.dev/docs/configuration/crds/v1beta1/logging_types/#loggingspec-nodeagents) that `nodeAgents` is going away soon. 

So, how do I enable and configure windows support? :)

Thank you.
