### DISCUSSION TITLE
How to parse a string to json in my healm's k8s

### DISCUSSION THREAD

**Discussion by heldergomes** [kube-logging/logging-operator#1724] [Q&A] [answered]
Hi Guys,

I am struggling to solve a problem, I have an application running in python, and every log that I raise is parsed to json, because I'd like to filter the fields of my log in the elastic search (kibana).

This application is running on k8s, and we use kube-logging to ingest the logs into kibana, however it seems that the datas of my logging is coming as text to kibana.

Is it possible parse the value of the field message from text to json in kube-logging configurations ? I think this would solve my problems.

**Comment by pepov** [comment, marked as answer]
you have to add an extra json parser and parse the json field as well, like this:
```
  - parser:
      key_name: message
      parse:
        type: json
      remove_key_name_field: true
      reserve_data: true
```
