### DISCUSSION TITLE
How to send logs to a PersistentVolume? (Rancher Logging Chart, File Output, PVC)

### DISCUSSION THREAD

**Discussion by loic-brtd** [kube-logging/logging-operator#1877] [Q&A] [answered]
Hi, I'm using the `rancher-logging` Chart via the Rancher Logging plugin. I'd like to create a [File Output](https://kube-logging.dev/docs/configuration/plugins/outputs/file/) to store logs into a volume. This might look something like this :

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: logs-file.output
  namespace: ns
spec:
  file:
    buffer:
      chunk_limit_size: 16MB
      flush_at_shutdown: true
      flush_interval: 5s
      flush_mode: interval
      flush_thread_count: 8
      overflow_action: drop_oldest_chunk
      retry_max_interval: 30s
      retry_timeout: 1h
      retry_type: exponential_backoff
    path: /var/nfs/logs/
```

But I don't know in which filesystem the logs are stored. Ideally, I'd like to store them inside an existing PersistentVolume, using a PVC (PersistentVolumeClaim) but I don't know how/where to configure this. Could you help me please?
