### DISCUSSION TITLE
Future Deprecations

### DISCUSSION THREAD

**Discussion by csatib02** [kube-logging/logging-operator#2055] [Announcements]
# Deprecations

We are planning on deprecating the following components in the next major release.

## 1. NodeAgent CRD and inline NodeAgents in the Logging resource

NodeAgents were an attempt to generalize log agents configuration, however it never grew out of a PoC where the main feature was the ability to run fluentbit on windows hosts. The code has not been updated and unfortunately the original fluentbit spec (in the Logging resource and in the separate FluentbitAgent resource) and the features behind it significantly diverged.

In the last year, [Telemetry Controller](https://github.com/kube-logging/telemetry-controller) was introduced as a replacement for both NodeAgent and FluentbitAgent resource with additional multi-tenant capabilities and more flexible agent side log selection in general.

Users of NodeAgent (should be Windows users mostly) are encouraged to get in contact with us (the maintainers) over [the community channels](https://kube-logging.dev/docs/community/) to find a viable path forward using the Telemetry Controller. 

Non-windows users should either migrate to FluentbitAgent or to the Telemetry Controller. Please also contact the community channels if you are in doubt!

### Timeline

NodeAgents will be removed with 6.0.0 coming in 14th of July, while 5.4.0 is officially supported until 6th of October. (The ability to release patches from community contributions for version 5.4.0 will be supported even after 6th of October.)

### Migration

from:

```yaml
  hostTailer:
    # -- HostTailer
    enabled: false
    # -- name of HostTailer
    name: hosttailer
    image:
      # -- repository of eventTailer image
      repository:
      # -- tag of eventTailer image
      tag:
      # -- pullPolicy of eventTailer image
      pullPolicy:
      # -- imagePullSecrets of eventTailer image
      imagePullSecrets: []
    # -- workloadMetaOverrides of HostTailer
    workloadMetaOverrides:
    # -- workloadOverrides of HostTailer
    workloadOverrides:
    # -- configure fileTailers of HostTailer
    # example:
    #   - name: sample-file
    #     path: /var/log/sample-file
    #     disabled: false
    #     buffer_max_size:
    #     buffer_chunk_size:
    #     skip_long_lines:
    #     read_from_head: false
    #     containerOverrides:
    #     image:
    fileTailers: []
    # -- configure systemdTailers of HostTailer
    # example:
    #   - name: system-sample
    #     disabled: false
    #     systemdFilter: kubelet.service
    #     maxEntries: 20
    #     containerOverrides:
    #     image:
    systemdTailers: **[]**
```

to:

```yaml
  hostTailers:
    # -- Enable all hostTailers
    enabled: false
    # -- List of hostTailers configurations
    instances: []
    # - name: hosttailer
      # -- Enable hostTailer
      # enabled: true
      # image:
        # -- repository of eventTailer image
        # repository:
        # -- tag of eventTailer image
        # tag:
        # -- pullPolicy of eventTailer image
        # pullPolicy:
        # -- imagePullSecrets of eventTailer image
        # imagePullSecrets: []
      # -- workloadMetaOverrides of HostTailer
      # workloadMetaOverrides: {}
      # -- workloadOverrides of HostTailer
      # workloadOverrides: {}
      # -- configure fileTailers of HostTailer
      # fileTailers:
      # - name: sample-file
      #   path: /var/log/sample-file
      #   disabled: false
      #   buffer_max_size:
      #   buffer_chunk_size:
      #   skip_long_lines:
      #   read_from_head: false
      #   containerOverrides:
      #   image:
      # -- configure systemdTailers of HostTailer
      # systemdTailers:
      # - name: system-sample
      #   disabled: false
      #   systemdFilter: kubelet.service
      #   maxEntries: 20
      #   containerOverrides:
      #   image:
    ```
