### DISCUSSION TITLE
logging-operator & Fleet

### DISCUSSION THREAD

**Discussion by hbouaziz** [kube-logging/logging-operator#925] [Q&A] [answered]
Hi ! am wondering if I can use logging-operator with fleet

**Comment by csatib02** [comment, marked as answer]
Hey @hbouaziz,
Sorry for the very late reply, you can absolutely use fleet to deploy the logging-operator:

```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging-operator
  namespace: fleet-local
spec:
  repo: "https://github.com/kube-logging/logging-operator"
  paths:
  - charts/logging-operator

```
