### ISSUE TITLE
ClusterOutput affinity to a certain fluentd?

### ISSUE THREAD

**Issue by vavdoshka** [kube-logging/logging-operator#1019]
**Is your feature request related to a problem? Please describe.**

Ideally, I want to describe all the logging config in one default namespace with only `ClusterFlow` and `ClusterOutput` resources. I need to send logs to both AWS Opensearch and S3, where S3 should get the full copy of all logs from all namespaces (archive) and AWS Opensearch should have only a selected portion from several namespaces (real time prioritized stuff).

By default, when I create two `ClusterOutput` resources with these two destinations, I see them added into one fluentd config.
So both log streams are processed through the same fluentd instance (or cluster). But this is what concerns me, I believe I have two entirely different use-cases there (real-time and archive), and I would want them to be processed by two distinct fluend instances to avoid sharing same resources and be able to properly monitor/size each of them.
One extra thing I've noticed is that for example, if OS is down, no logs are sent in S3. Not sure what is causing this.

**Describe the solution you'd like**
Something like `ClusterOutput` affinity to a certain `Logging` cluster would make it work. BTW When one deploys `Logging` can it come with fluentd only?
Or maybe there is some existing way of doing that somehow.

**Describe alternatives you've considered**
* Probably it is possible to achive if deploy `Logging` in two different dedicated special namespaces and use `Flow` and `Output` correspondingly? Less preferable to have some special namespaces just for that.
* Use AWS Firehose as a single point of destination and route S3/OS from there - extra component, more costs.

**Additional context**

Current config
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default
  namespace: logging
spec:
  fluentd:
    image:
      repository: banzaicloud/fluentd
      tag: v1.11.5-alpine-24
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: REDACTED-role
  fluentbit: {}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: selected-logs-to-aws-es
  namespace: logging
spec:
  match:
  - select:
      namespaces:
        - ns-1
        - ns-2
        - etc
  globalOutputRefs:
    - aws-es
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs-to-aws-s3
  namespace: logging
spec:
  globalOutputRefs:
    - aws-s3
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: aws-es
  namespace: logging
spec:
  awsElasticsearch:
    endpoint:
      url: REDACTED-url
      region: us-east-1
      assume_role_arn:
        value: REDACTED-role
      assume_role_web_identity_token_file:
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    index_name: logs-${$.kubernetes.namespace_name}-%Y.%m.%d
    log_es_400_reason: true
    buffer:
      tags: tag,time,$.kubernetes.namespace_name
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: aws-s3
  namespace: logging
spec:
  s3:
    assume_role_credentials:
      role_arn: REDACTED-role
      role_session_name: fluentd
    s3_bucket: REDACTED-bucket
    s3_region: us-east-1
    path: ${$.kubernetes.namespace_name}/%Y/%m/%d/%H/%M
    s3_object_key_format: "%{path}/%{time_slice}_%{uuid_flush}_%{index}.%{file_extension}"
    buffer:
      tags: tag,time,$.kubernetes.namespace_name
      timekey: 10m
      timekey_wait: 30s
      timekey_use_utc: true
```

This is a digramm of what I want to achive basically:

![image](https://user-images.githubusercontent.com/11683992/170504000-1c33f89d-8e27-4369-b290-794e53d78453.png)
