### ISSUE TITLE
fluentd configcheck failed for multi worker

### ISSUE THREAD

**Issue by sureshgoli25** [kube-logging/logging-operator#1023]
Hi, I am trying to configure multi worker as per documentation. However, i am getting permission denied error from config check.

Helm Chart Version: v3.17.4
Environment: Rancher 2.6.3
Config Check pod log:
```
2022-05-27 11:37:19 +0000 [info]: starting fluentd-1.14.5 as dry run mode ruby="2.7.5"
/usr/lib/ruby/2.7.0/fileutils.rb:247:in `mkdir': Permission denied @ dir_s_mkdir - /buffers/worker0 (Errno::EACCES)
        from /usr/lib/ruby/2.7.0/fileutils.rb:247:in `fu_mkdir'
        from /usr/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
        from /usr/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
        from /usr/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
        from /usr/lib/ruby/2.7.0/fileutils.rb:211:in `each'
        from /usr/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin_id.rb:80:in `plugin_root_dir'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin/buf_file.rb:63:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin/output.rb:379:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-grafana-loki-1.2.18/lib/fluent/plugin/out_loki.rb:83:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/label.rb:31:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `block in configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `each'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:665:in `run_supervisor'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
        from /usr/bin/fluentd:23:in `load'
        from /usr/bin/fluentd:23:in `<main>'
```

Below is the configuration.
```
cl-flow
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cl002-cluster-flow
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
  - cl-cluster-output
  match:
  - select: {}
  filters:
  - record_modifier:
      records:
        - fluentd_worker: "#{worker_id}"
```
```
cl-output
---
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cl-cluster-output
  namespace: cattle-logging-system
spec:
  loki:
    buffer:
      chunk_limit_size: 1M
      flush_at_shutdown: true
      flush_interval: 1s
      flush_mode: interval
      retry_forever: true
      retry_type: periodic
      retry_wait: 10s
      path: ${root_dir}/worker${worker index}/${plugin @id}/buffer
    configure_kubernetes_labels: true
    insecure_tls: true
    url: http://loki.logging.svc.cluster.local:3100
    tenant: cl-all-pods-logs
```
```
Logging Resource Spec:
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: rancher-logging-root
spec:
  allowClusterResourcesFromAllNamespaces: false
  controlNamespace: cattle-logging-system
  fluentbit:
    image:
      repository: rancher/mirrored-fluent-fluent-bit
      tag: 1.8.15
    inputTail:
      Buffer_Chunk_Size: 1MB
      Buffer_Max_Size: 10MB
      Mem_Buf_Limit: 10MB
      Skip_Long_Lines: "Off"
    nodeSelector:
      kubernetes.io/os: linux
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  fluentd:
    bufferStorageVolume:
      emptyDir:
        medium: Memory
    configReloaderImage:
      repository: rancher/mirrored-jimmidyson-configmap-reload
      tag: v0.4.0
    disablePvc: true
    fluentOutLogrotate:
      age: "10"
      enabled: true
      path: /buffers/logs/out
      size: "10485760"
    image:
      repository: rancher/mirrored-banzaicloud-fluentd
      tag: v1.14.5-alpine-1
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      tcpSocket:
        port: 24240
    logLevel: debug
    nodeSelector:
      kubernetes.io/os: linux
    rootDir: /buffers
    security:
      podSecurityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    workers: 8
  watchNamespaces:
  - cattle-logging-system
```

Am i doing something worng.
