### ISSUE TITLE
logging fluentbit inputTail Buffer_Max_Size are invalid

### ISSUE THREAD

**Issue by gulin90** [kube-logging/logging-operator#1036]
In my use case, i'm using the fluentbit to read Kubernetes pod logs, and sometimes these logs are very long. 

For example: my single-line log size reaches 100k, which is larger than 32k.  And these logs must be collected and cannot be discarded, so I have to increase the Buffer_Max_Size value. but logging fluentbit inputTail Buffer_Max_Size are invalid

#### Logging config
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
.....
spec:
  fluentbit:
    inputTail:
      Buffer_Max_Size: 2MB
      Mem_Buf_Limit: 20MB
```
#### fluentbit secret
```

[SERVICE]
    Flush        1
    Grace        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    Coro_Stack_Size    24576
    storage.path  /buffers

[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    Mem_Buf_Limit  20MB
    Parser  docker
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  On
    Tag  kubernetes.*
```
