### ISSUE TITLE
extraVolumes PVC provisioning does not work on fluentd statefulset

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1063]
**Describe the bug**:
PVC ExtraVolumes are not well added on Fluentd statefulset.

**Expected behaviour**:

I want the ExtraVolume to add a PVC as a volumeClaimTemplate so I get one extra volume per fluentd replicas.

**Steps to reproduce the bug**:

- Deploy a default Logging with no customization:
- Update with the following extraVolumes definition:
```yaml
          fluentd:
            # Adding an extra volume for discarded chunks so they doesn't fills up the host disk
            extraVolumes:
              - volumeName: discarded-chunks
                path: "/tmp/fluent/backup"
                containerName: fluentd
                volume:
                  pvc:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 10Gi
                      storageClassName: standard
                      volumeMode: Filesystem
```
- STS is well updated with the volumeMounts section
  ```
          volumeMounts:
          - mountPath: /tmp/fluent/backup
          name: discarded-chunks
  ```
- STS is wrongly updated with the volume section
  ```
      volumes:
      - name: discarded-chunks
        persistentVolumeClaim:
          claimName: ""
  ```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.20.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): RKE
- logging-operator version (e.g. 2.1.1): 3.17.8
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): 

```
logging-operator-controller-7b74cb7789-vcxhm logging-operator 1.6587585880864148e+09    DEBUG   controllers.Logging     resource diff   {"name": "logging-operator-logging-fluentd", "namespace": "logging", "apiVersion": "apps/v1", "kind": "StatefulSet", "patch": "{\"spec\":{\"template\":{\"spec\":{\"$setElementOrder/containers\":[{\"name\":\"fluentd\"},{\"name\":\"config-reloader\"},{\"name\":\"buffer-metrics-sidecar\"}],\"$setElementOrder/volumes\":[{\"name\":\"config\"},{\"name\":\"app-config\"},{\"name\":\"output-secret\"},{\"name\":\"fluentd-tls\"},{\"name\":\"discarded-chunks\"}],\"containers\":[{\"$setElementOrder/volumeMounts\":[{\"mountPath\":\"/fluentd/etc/\"},{\"mountPath\":\"/fluentd/app-config/\"},{\"mountPath\":\"/fluentd/secret\"},{\"mountPath\":\"/fluentd/tls/\"},{\"mountPath\":\"/buffers\"},{\"mountPath\":\"/tmp/fluent/backup\"}],\"name\":\"fluentd\",\"volumeMounts\":[{\"mountPath\":\"/tmp/fluent/backup\",\"name\":\"discarded-chunks\"}]}],\"volumes\":[{\"name\":\"discarded-chunks\"},{\"$patch\":\"delete\",\"name\":\"extravolume-0\"}]}}}}"}
```

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: See above

- Solving tracks:
  - Add `volumeClaimTemplate` to StatefulSetSpec instead of adding `volumes` to the PodSpec. Keep adding `volumeMounts` to the PodSpec.

/kind bug
