### ISSUE TITLE
spec.fluentd.bufferVolumeMetrics.serviceMonitorConfig ignored by operator

### ISSUE THREAD

**Issue by RafalMaleska** [kube-logging/logging-operator#1070]
**Describe the bug**:

When customizing the ServiceMonitor for fluentd bufferVolume with: 

```
  fluentd:
    bufferVolumeImage:
      imagePullSecrets:
        - name: pull-secret
      repository: registry.com/logging/node-exporter
      tag: v1.1.2
    bufferVolumeMetrics:
      prometheusRules: true
      serviceMonitor: true
      serviceMonitorConfig:
        scheme: https
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          insecureSkipVerify: true
          keyFile: /etc/prom-certs/key.pem
    configCheckAnnotations:
      sidecar.istio.io/inject: "false"
    configCheckResources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 16Mi
    configReloaderImage:
      repository: registry.com/configmap-reload
      tag: v0.5.0
    configReloaderResources:
      limits:
        cpu: 20m
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 16Mi
    fluentOutLogrotate:
      age: "10"
```

the operator creates following service monitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helix-fluentd-buffer-metrics
  namespace: helix-logging
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    port: buffer-metrics
  namespaceSelector:
    matchNames:
    - helix-logging
  selector:
    matchLabels:
      app.kubernetes.io/component: fluentd
      app.kubernetes.io/managed-by: helix
      app.kubernetes.io/name: fluentd
```

ignoring the serviceMonitorConfig under bufferVolumeMetrics

**Expected behaviour**:

ServiceMonitor created similar to: 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helix-fluentd-buffer-metrics
  namespace: helix-logging
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    port: buffer-metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/prom-certs/key.pem
  namespaceSelector:
    matchNames:
    - helix-logging
  selector:
    matchLabels:
      app.kubernetes.io/component: fluentd
      app.kubernetes.io/managed-by: helix
      app.kubernetes.io/name: fluentd
```

**Steps to reproduce the bug**:

1. Install logging-operator
2. Create above logging resource
3. Check the created ServiceMonitor

**Environment details**:
- Kubernetes version: v1.21.1:
- Cloud-provider/provisioner: PKS
- logging-operator version: 3.17.0
- Install method: helm + kustomize

Logs from Operator: 

```
{"level":"info","ts":1660044335.000565,"msg":"Waited for 1.197281733s due to client-side throttling, not priority and fairness, request: GET:https://10.100.192.1:443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s\n"}
{"level":"info","ts":1660044336.4026258,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1660044336.5085297,"logger":"setup","msg":"Detected container runtime","runtime":"docker"}
{"level":"info","ts":1660044336.5085607,"logger":"setup","msg":"Unable to detect container runtime, keeping default value","runtime":"docker"}
{"level":"info","ts":1660044336.508783,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1660044336.5095165,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1660044336.5096598,"msg":"attempting to acquire leader lease helix-logging/logging-operator.logging.banzaicloud.io...\n"}
{"level":"info","ts":1660044352.9630206,"msg":"successfully acquired lease helix-logging/logging-operator.logging.banzaicloud.io\n"}
{"level":"info","ts":1660044352.9632788,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.963324,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633307,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633355,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633408,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633458,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633505,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633553,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633608,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633756,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633832,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633899,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9633994,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634056,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634187,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634256,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.963432,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.963439,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.963445,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634519,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634616,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634683,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634764,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634836,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634888,"logger":"controller-runtime.manager.controller.logging","msg":"Starting EventSource","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9634974,"logger":"controller-runtime.manager.controller.logging","msg":"Starting Controller","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging"}
{"level":"info","ts":1660044352.9637766,"logger":"controller-runtime.manager.controller.eventtailer","msg":"Starting EventSource","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"EventTailer","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9637978,"logger":"controller-runtime.manager.controller.eventtailer","msg":"Starting Controller","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"EventTailer"}
{"level":"info","ts":1660044352.9639134,"logger":"controller-runtime.manager.controller.hosttailer","msg":"Starting EventSource","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"HostTailer","source":"kind source: /, Kind="}
{"level":"info","ts":1660044352.9639325,"logger":"controller-runtime.manager.controller.hosttailer","msg":"Starting Controller","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"HostTailer"}
{"level":"info","ts":1660044359.301548,"logger":"controller-runtime.manager.controller.eventtailer","msg":"Starting workers","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"EventTailer","worker count":1}
{"level":"info","ts":1660044359.3017213,"logger":"controller-runtime.manager.controller.hosttailer","msg":"Starting workers","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"HostTailer","worker count":1}
{"level":"info","ts":1660044359.398563,"logger":"controller-runtime.manager.controller.logging","msg":"Starting workers","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","worker count":1}
{"level":"info","ts":1660044359.9975488,"logger":"KubeAPIWarningLogger","msg":"policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+"}
{"level":"info","ts":1660044361.0997367,"logger":"controllers.Logging","msg":"resource created","name":"helix-fluentd-buffer-metrics","namespace":"helix-logging"}
{"level":"info","ts":1660044361.8971486,"msg":"Notice: If the Buffer_Size value is empty we will set it 0. For more information: https://github.com/fluent/fluent-bit/issues/2111"}
{"level":"info","ts":1660044361.8973448,"msg":"Notice: Because the Fluentd statefulset has been scaled, we've made some changes in the fluentbit network config too. We advice to revise these default configurations."}
```

/kind bug
