### ISSUE TITLE
Operator buffers filtered messages, but does not send to external endpoints. 

### ISSUE THREAD

**Issue by jmarhee** [kube-logging/logging-operator#1074]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Logs are filtered, and buffers populated as expected. However, nothing is received by any external syslog endpoints. An internal (to the cluster) syslog instance receives logs as expected. Raising logLevel to debug, no additional log data is provided. Confirmed the application pods can connect to the external syslog endpoint over the specified port and protocol, and that the CLusterFlow and Output are active with no problems. 

Note: I attempted to raise this first in community Slack, but signup seems to be restricted to employee domains-- let me know if this is not the case, and I can raise it somewhere as appropriate and close this. 

**Expected behaviour**:
The collected and buffered log lines sent to/received by external logging endpoint. This occurs normally when the syslog endpoint is inside the cluster.

**Steps to reproduce the bug**:
Install logging operator, apply ClusterOutput, apply ClusterFlow, applications begin sending logs. 

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.19.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 3.17.4 
- Install method (e.g. helm or static manifests): Helm (Rancher)
- Logs from the misbehaving component (and any other relevant logs): Below
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: Below

```
---
# Source: rancher-logging-outputs/templates/clusteroutput.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: syslog01.suse
  namespace: cattle-logging-system
spec:
  syslog:
    buffer:
      total_limit_size: 2GB
      flush_thread_count: 8
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 1m
    format:
      app_name_field: kubernetes.pod_name
      hostname_field: kubernetes.host
      log_field: log
      rfc6587_message_size: false
    host: {URL}
    insecure: true
    port: 514
    transport: udp
---
# Source: rancher-logging-flows/templates/clusterflow.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: syslog01.suse
  namespace: cattle-logging-system
spec:
  filters:
  - grep:
      regexp:
      - key: log
        pattern: "/(SIEM(?:-APP)?)/"
  globalOutputRefs:
  - syslog01.suse
  ```
  
 Using the default Logging resource from the Rancher chart: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/100.1.2%2Bup3.17.4/templates/loggings/root/logging.yaml
  
 Logs from fluentd, and this message continuously only occurs when the endpoint is an external hostname (which is reachable from the pods over the specified protocol and port), and not internal to the cluster (i.e. syslog.default), otherwise, this message does not appear in the logs:
 
 ```
$ kubectl exec -it -n cattle-logging-system rancher-logging-root-fluentd-0 -c fluentd -- tail /fluentd/log/out                                                2022-08-19 15:11:16 +0000 [warn]: #0 [main_forward] incoming chunk is broken: host="10.244.189.241" msg=48   
 ```

/kind bug
