### ISSUE TITLE
ssl_version is not working for Opensearch Outputs

### ISSUE THREAD

**Issue by jadhavnitind** [kube-logging/logging-operator#1088]
**Describe the bug**:
Earlier I was using Elasticsearch for logging  purpose under output spec. Now I see that there is support available for Openreach plugin as well so I have upgrade operator to latest version that is 3.17.8 but when I have added ssl_version field under OpenSearch it is giving me error.
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
 name: dp-logging-stdout
spec:
  opensearch:
    host: opensearch-cluster-master.logging.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    index_name: "dp-app"
    user: admin
    password:
      valueFrom:
        secretKeyRef:
          name: opensearch-credentials
          key: password
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
```

**Expected behaviour**:
The output should accept the ssl_version field.

**Steps to reproduce the bug**:
Install latest logging operator on Kubernetes and try to run above output yaml file which will give you error.
```
$ kubectl apply -f dp/dp-logging-opensearch.yaml 
error: error validating "dp/dp-logging-opensearch.yaml": error validating data: ValidationError(Output.spec.opensearch): unknown field "ssl_version" in io.banzaicloud.logging.v1beta1.Output.spec.opensearch; if you choose to ignore these errors, turn validation off with --validate=false
```
**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.22
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 3.17.8
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
