### ISSUE TITLE
Multiworker support for aggregated_metrics endpoint in servicemonitor

### ISSUE THREAD

**Issue by buddyledungarees** [kube-logging/logging-operator#1110]
**Describe the bug**:

Not sure if this is a bug or feature request since official support for multi workers is unclear. But since the fluentdSpec supports specifying workers count, I'm proceeding with a bug report.

When using multi-workers, metrics are now generated per worker process with a new label, worker_id. The metric endpoint is actually incremented by worker_id above worker0's port, which is the value defined in the prometheus source.

There is an [aggregated endpoint](https://github.com/fluent/fluent-plugin-prometheus/blob/1f67114fbbae619f9ccc422b1d558efc3d658150/README.md#prometheus-input-plugin) at default path `/aggregated_metrics` that can be scraped by prometheus for all workers.

Unfortunately, there doesn't seem to be a way to override the serviceMonitor's config for metrics endpoint since it uses the same variable as the metrics path, which we don't want to change.

**Expected behaviour**:
The servicemonitor object should see if there are more than one worker and use the aggregated metrics endpoint instead.

**Steps to reproduce the bug**:

1. Set workers to > 1
2. Notice that prometheus metrics only have timeseries for worker_id = 0 (first worker)

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Rancher + EKS
- logging-operator version (e.g. 2.1.1): 3.17.4
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): N/A
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

Logging object:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: banzaiLogging
spec:
  fluentbit:
  #<...snip...>
  fluentd:
    livenessDefaultCheck: true
    logLevel: warn
    metrics:
      path: /metrics
      port: 24231
      serviceMonitor: true
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: "1"
        memory: 512Mi
    rootDir: /buffers
    scaling:
      replicas: 10
    security:
      roleBasedAccessControlCreate: true
    workers: 2
```

Resultant serviceMonitor object:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
#<...snip...>
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 15s
    path: /metrics
    port: http-metrics
    scrapeTimeout: 5s
  namespaceSelector:
    matchNames:
    - namespace_name
  selector:
    matchLabels:
      app.kubernetes.io/component: fluentd
      app.kubernetes.io/name: fluentd
```

/kind bug
