### ISSUE TITLE
Remove nested fields

### ISSUE THREAD

**Issue by lulukas86** [kube-logging/logging-operator#1129]
Hi there

I need to remove nested fields using fluentd (or fluentbit). I have the following Flow deployed, but it doesn't remove the field _kubernetes.pod_id_

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
 ...
spec:
  filters:
  - record_modifier:
      remove_keys: ${record["kubernetes"]["pod_id"]}
  localOutputRefs:
  - splunk-output
  match:
  - exclude:
      container_names:
      - istio-proxy
  - select: {}
```
Also with configuring Fluentbit, it didn't work:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
...
spec:
...
  fluentbit:
    filterModify:
    - rules:
      - Remove:
          key: $.kubernetes.pod_id

```
I saw different suggestions, like https://github.com/repeatedly/fluent-plugin-record-modifier/issues/15 but none worked for me. I'm using v3.17.9. Any help is appreciated.

**Comment by laconictae** [comment]
Hi @lulukas86 - I don't know if you ever got what you need for this but I was trying to do a very similar thing removing nested fields and eventually got it working with a `record_transfomer` filter instead. Maybe there is a bug with `record_modifier`, who knows. Here's what I did to successfully remote the "annotations" section:

```
spec:
  filters:
  - record_transformer:
      remove_keys: $.kubernetes.annotations
```

**Comment by lulukas86** [comment]
I could solve it like that:
```
spec:
  filters:
  - record_transformer:
      remove_keys: $["kubernetes"]["labels"]["security.istio.io/tlsMode"], $["kubernetes"]["annotations"]
```
That removes the kubernetes label `security.istio.io/tlsMode` and all kubernetes annotations)
