### ISSUE TITLE
logging-operator restarts encountered

### ISSUE THREAD

**Issue by BaskiGIT** [kube-logging/logging-operator#1130]
**Describe the bug**:
We noted restarts happening for logging-operator often. OOMKilled does not seem to have the issue. cpu usage was also well within the limits.

**Expected behaviour**:
To not restart or give more detailed logs for the restarts.

**Steps to reproduce the bug**:
Just keep logging-operator running.

**Environment details**:
- Kubernetes version: 1.21.14-gke.3000
- Cloud-provider/provisioner: GKE
- logging-operator version: 3.17.4@sha256:60a670b48bf4d6f642394b90c95be86f916e2e29e3b737360668b5f7895bdbe5
- Install method: static manifests
- Logs from the misbehaving component (and any other relevant logs):

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/17687380/200358335-b4cd23a3-2f41-4f85-a741-10ddb51184df.png">

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/17687380/200358827-0e004ef2-def0-4d00-bdf6-fc28013418b0.png">

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/17687380/200359530-193e3954-256e-43dd-acab-10d81223e878.png">

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/17687380/200360316-4765f9b3-ca75-4ff0-a62b-3b7f9dbaa0e6.png">
    
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

   ```
    name: logging-operator
    image: ghcr.io/banzaicloud/logging-operator
    imagePullPolicy: IfNotPresent
    args:
      - -enable-leader-election=true
    ports:
    resources:
      requests:
        cpu: 50m
        memory: 192Mi
      limits:
        cpu: 50m
        memory: 192Mi
     ```

/kind bug
