### ISSUE TITLE
Fluentd scaling drain support labels

### ISSUE THREAD

**Issue by ekhaydarov** [kube-logging/logging-operator#1141]
**Is your feature request related to a problem? Please describe.**
When using istio envoy sidecars, they are injected in every pod. However, the scaling drain job starts with envoy sidecar being injected, however it is never killed like the other containers in the job so it just stays alive.  We can set the scaling drain annotation as seen [here](https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/drainjob.go#L46). However, we cannot do the same for labels, which is what istio uses to stop injecting sidecars.

**Describe the solution you'd like**
It would be great if in the fluentd config yaml we can set labels like we already can set annotations. We would simply like to move that annotation into labels and the lable be passed into the job [here](https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/drainjob.go#L45)
```
fluentd:
  scaling:
    replicas: 2
    drain:
      enabled: true
      annotations:
        sidecar.istio.io/inject: false
```

**Describe alternatives you've considered**
We have tried with the annotation but it has already been deprecated by istio in favour of labels
