### ISSUE TITLE
Loki output: set tenant header based on k8s label instead of static value

### ISSUE THREAD

**Issue by atamgp** [kube-logging/logging-operator#1145]
**Describe the solution you'd like**
I want to define 1 default Loki ClusterOutput but not with a static tenant. 
With this, tenants don't get to see the config (it's cluster level) and for 100 tenant's I don't need then to create 100 namespaced output's with the same  loki endpoint and auth config with is unsecure and harder to maintain if something changes.

e.g.:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: default
spec:
 loki:
   url: http://loki:3100
   tenant_from_label: "capsule.clastix.io/tenant"
   configure_kubernetes_labels: true
   buffer: ...
```

**Additional context**
We create multi tenant k8s clusters and use [capsule](https://capsule.clastix.io/) to create Tenant's in the cluster. 
It's not relevant to know how Capsule works internally, only that namespaces and pods have a certain label with their tenant id.

For logging, I need to extract this label to be forwarded as the tenant header (X-Scope-OrgId) to Loki.

I see in the code that something like this is available for **kafka** (headers_from_record in the crds):
```
              kafka:
                properties:
                  ack_timeout:
                    type: integer
...
                  headers_from_record:
                    additionalProperties:
                      type: string
                    type: object
```
                    
                    
More important: **Fluentd** also supports this:
[https://docs.fluentd.org/output/http#headers_from_placeholders](https://docs.fluentd.org/output/http#headers_from_placeholders)

For non-loki users it might be interesting to also add this feature (with a more generic name: headers_from_record) to the **http** output
