### ISSUE TITLE
custom-runner HTTP endpoint not available, waiting

### ISSUE THREAD

**Issue by Gholie** [kube-logging/logging-operator#1231]
Trying to use the drain config to remove buffer when scaling down, getting the above error. My fluentd config looks like this:
```YAML
fluentd:
    logLevel: warn
    resources:
      limits:
        memory: 6Gi
        cpu: 2000m
    metrics:
      prometheusRules: true
      serviceMonitor: true
      serviceMonitorConfig:
        additionalLabels:
          release: kube-prometheus-stack
    livenessDefaultCheck: true
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: managed-csi-premium-retain
          volumeMode: Filesystem
    # bufferVolumeMetrics:
    #   prometheusRules: true
    #   serviceMonitor: true
    #   serviceMonitorConfig:
    #     additionalLabels:
    #       release: kube-prometheus-stack
    fluentOutLogrotate:
      enabled: true
      path: /fluentd/log/out
      age: "10"
      size: "10485760"
    image:
      repository: myregistry.io/fluent/fluentd
      tag: v1.14.6-alpine-5
    configReloaderImage:
      repository: myregistry.io/jimmidyson/configmap-reload
      tag: v0.7.1
    # bufferVolumeImage:
    #   repository: myregistry.io/banzaicloud/custom-runner
    #   tag: v0.2.0
    scaling:
      replicas: 2
      drain:
        enabled: true
        image:
          repository: myregistry.io/log/fluentd-drain-watch
          tag: v0.2.0
        pauseImage:
          repository: myregistry.io/log/pause
          tag: latest
    # Security settings
    security:
      # containerSecurityContext - Needs to run as root
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
      # podSecurityContext
      podSecurityContext:
        fsGroup: 101
```

Images are copied from the official repo
