### ISSUE TITLE
buffer-metrics-sidecar broken

### ISSUE THREAD

**Issue by genofire** [kube-logging/logging-operator#1250]
**Describe the bug**:
custom-runner has no shell to start node-exporter

**Expected behaviour**:
node-exporter is started

**Steps to reproduce the bug**:
- helm values:
```yaml
fluentd:
  bufferVolumeMetrics:
    prometheusRules: true
    serviceMonitor: true
    serviceMonitorConfig:
      additionalLabels:
        prometheus: default
```
  - container has args:
    ```yaml
    args:
      - --startup
      - ./bin/node_exporter --web.listen-address=:9200 --collector.disable-defaults
        --collector.filesystem
    ```
  - show log (no logs from node-exporter):
    ```
    listening on port:7357
    ```
- test from fluentd container, run:
  - `curl localhost:7357` -> works ('with 404')
  - `curl localhost:9200` -> failed ('with Connection refused')

**Additional context**:
looks like **custom-runner** is a image `from scratch`, but need shell to run `node-exporter`
https://github.com/kube-logging/custom-runner/blob/a42c241ccf7f50d84a8767951401f82e7012e4bd/src/api/exec.go#L28

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): own
- logging-operator version (e.g. 2.1.1): v0.4.0
- Install method (e.g. helm or static manifests): helm
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
