### ISSUE TITLE
Logging - defaultFlow does not work

### ISSUE THREAD

**Issue by genofire** [kube-logging/logging-operator#1259]
**Describe the bug**:

defining defaultFlow:
```yaml
defaultFlow:
  name: "default"
  spec:
    filters:
      - prometheus:
          metrics:
            - name: "logs_namespace_count"
              desc: "The total number of message in namespace"
              type: "counter"
          labels:
            exported_namespace: "$.kubernetes.namespace_name"
    globalOutputRefs:
      - "default"
```
and (with an match):
```yaml
defaultFlow:
  name: "default"
  spec:
    filters:
      - prometheus:
          metrics:
            - name: "logs_namespace_count"
              desc: "The total number of message in namespace"
              type: "counter"
          labels:
            exported_namespace: "$.kubernetes.namespace_name"
    match:
      - exclude:
          labels:
            do-not-log: "true"
    globalOutputRefs:
      - "default"
```

gives following logs in configcheck:
```
Missing <match> sections in <label @...> section
```

**Expected behaviour**:
Do not know -> thats why i have clusterflow with many exclude for existings flows - see #1242

**Environment details**:
- logging-operator version (e.g. 2.1.1): v4.0.0
- Install method (e.g. helm or static manifests): helm

/kind bug
