### ISSUE TITLE
Can't stream eks logs to different AWS account.

### ISSUE THREAD

**Issue by helenrai** [kube-logging/logging-operator#1275]
I have been trying to stream EKS Logs to cloudwatch. The EKS cluster account and logs account are different. I have used banzai cloud to do this in managed cluster and it is working fine there. Not been able to recreate this on EKS.
I followed these steps.
https://banzaicloud.com/docs/one-eye/logging-operator/examples/cloudwatch-nginx/
Is there any additional steps we need to do for EKS?
Here are the manifests
clusteroutput :
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: api-output
 namespace: logging
spec:
 cloudwatch:
   aws_key_id:
     valueFrom:
       secretKeyRef:
         name: logging-cloudwatch
         key: awsAccessKeyId
   aws_sec_key:
     valueFrom:
       secretKeyRef:
         name: logging-cloudwatch
         key: awsSecretAccessKey
   log_group_name: api
   log_stream_name: api-logging
   region: us-east-1
   auto_create_stream: true
   buffer:
     timekey: 5s
     timekey_wait: 5s
     timekey_use_utc: true
```
clusterflow:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: api-clusterflow
  namespace: logging
spec:
  globalOutputRefs:
    - api-output
  match:
    - exclude:
        namespaces:
          - amazon-cloudwatch
          - screenshot
    - select:
        labels:
          app: api
```
logging:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging
  ```
