### ISSUE TITLE
Incorrect host in DataDog Output

### ISSUE THREAD

**Issue by argais** [kube-logging/logging-operator#1317]
I'd join the slack group to ask about this, but it seems to be restricted.

**Describe the bug**:
I have the logging operator deployed, with a single clusterflow and cluster output sending everything to datadog.

It works for the most part, I get my logs and everything looks good, but the host field for the logs comes populated with the headless service name of the fluentd instance forwarding the logs instead of the actual node name where the log came from. Which makes it impossible to correlate the logs to the nodes in the datadog UI. Host is an immutable field in datadog, so I need to fix it in cluster.

**Expected behaviour**:
I'd expect that the host field is populated with the kubernetes node name where the log came originally from.

**Steps to reproduce the bug**:
- deploy the logging operator
- create a secret with a datadog api key
- create a cluster output to datadog pointing the api_key to the secret as described in the documentation
- create a cluster flow with dedot and tag normaliser
- create a logging resource

**Additional context**:
Other than this issue the logs are showing up just fine :) 

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.25.6-eks-48e63af
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): chart v3.17.10
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): nothing really out of place in the logs for any of the components.
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

cluster output
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: default-output
  namespace: addon-logging-operator
spec:
  datadog:
    api_key:
      valueFrom:
        secretKeyRef:
          key: dd_api
          name: datadog-api-key
    buffer:
      chunk_limit_records: 500
      chunk_limit_size: 20m
      flush_interval: 3s
      timekey: 5s
      timekey_wait: 2s
      type: memory
    dd_source: kubernetes
    dd_tags: env:testing,cluster:eks-testing-us-west-2,kube_cluster_name:eks-testing-us-west-2
```

cluster flow
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: default-flow
  namespace: addon-logging-operator
spec:
  filters:
  - dedot:
      de_dot_nested: true
      de_dot_separator: '-'
  - tag_normaliser:
      format: ${namespace_name}.${pod_name}.${container_name}
  globalOutputRefs:
  - default-output
```

logging
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging
spec:
  controlNamespace: addon-logging-operator
  defaultFlow:
    globalOutputRefs:
    - default-output
  fluentbit:
    bufferStorageVolume:
      emptyDir:
        medium: Memory
    filterKubernetes:
      Buffer_Size: 8MB
      Kube_URL: https://kubernetes.default.svc:443
      Match: kubernetes.*
    logLevel: info
    podPriorityClassName: system-node-critical
    positiondb:
      emptyDir:
        medium: Memory
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    tolerations:
    - operator: Exists
  fluentd:
    bufferStorageVolume:
      emptyDir:
        medium: Memory
        sizeLimit: 768Mi
    fluentOutLogrotate:
      age: "10"
      enabled: true
      path: /fluentd/log/out
      size: "10485760"
    logLevel: info
    podPriorityClassName: system-cluster-critical
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    scaling:
      replicas: 2
```

/kind bug
