### ISSUE TITLE
banzaicloud/log-generator:0.3.2 can't pull

### ISSUE THREAD

**Issue by chuanbai** [kube-logging/logging-operator#1325]
crictl pull banzaicloud/log-generator:0.3.2

**Comment by pepov** [comment]
it should be:
```
docker pull ghcr.io/kube-logging/log-generator:v0.4.1
```

**Comment by chuanbai** [comment]
1 root@k8s-master01:~# kubectl -n logging  get pods
NAME                                                  READY   STATUS      RESTARTS   AGE
default-logging-simple-fluentbit-6dc9r                1/1     Running     0          8h
default-logging-simple-fluentd-0                      2/2     Running     0          8h
default-logging-simple-fluentd-configcheck-342aabec   0/1     Completed   0          8h
grafana-7cfd96944c-xfdxr                              1/1     Running     0          17h
log-generator-f999b5db6-sdzmk                         1/1     Running     0          9s
logging-operator-69b48dbf9d-85msp                     1/1     Running     0          17h
loki-0                                                1/1     Running     0          17h

2 root@k8s-master01:~# kubectl logs log-generator-f999b5db6-sdzmk  -n logging -f
time="2023-05-05T09:06:39Z" level=warning msg="Error reading config file, Config File \"config\" Not Found in \"[/conf]\""
Using config: 
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> main.main.func1.1 (1 handlers)
[GIN-debug] GET    /metrics                  --> main.promHandler.func1 (1 handlers)
[GIN-debug] GET    /state                    --> main.(*State).stateGetHandler-fm (1 handlers)
[GIN-debug] PATCH  /state                    --> main.(*State).statePatchHandler-fm (1 handlers)
[GIN-debug] GET    /state/memory             --> main.(*State).memoryGetHandler-fm (1 handlers)
[GIN-debug] PATCH  /state/memory             --> main.(*State).memoryPatchHandler-fm (1 handlers)
[GIN-debug] GET    /state/cpu                --> main.(*State).cpuGetHandler-fm (1 handlers)
[GIN-debug] PATCH  /state/cpu                --> main.(*State).cpuPatchHandler-fm (1 handlers)
[GIN-debug] GET    /state/log                --> main.(*State).logLevelGetHandler-fm (1 handlers)

3 this pod(log-generator-f999b5db6-sdzmk) will produce a lot of nginx logs?

**Comment by pepov** [comment]
what is this log? what are you trying to do exactly? which chart have you installed?

**Comment by jeremych1000** [comment]
I used the log-generator helm chart [here](https://github.com/kube-logging/helm-charts/tree/main/charts/log-generator) but am also a bit confused.

With the default values of the chart, it just prints that [GIN-debug] stuff at the beginning, but never actually prints any logs?

I tried setting count to 1 (0 is default which I assumed meant infinitely), but then it just printed one line of logs and exit 0'ed.

Is there a source code repo maybe?

**Comment by jeremych1000** [comment]
> I used the log-generator helm chart [here](https://github.com/kube-logging/helm-charts/tree/main/charts/log-generator) but am also a bit confused.
> 
> With the default values of the chart, it just prints that [GIN-debug] stuff at the beginning, but never actually prints any logs?
> 
> I tried setting count to 1 (0 is default which I assumed meant infinitely), but then it just printed one line of logs and exit 0'ed.
> 
> Is there a source code repo maybe?

Played around with it - it's not the most intuitive but got it working. I just set the count to a huge number and it generates logs now.

```
app:
  # Minimum interval between log messages (ms) (Default: 100)
  minInterval: 100
  # minInterval: 100
  # Maximum interval between log messages (s) (Default: 1)
  maxInterval: 5
  # maxInterval: 1
  # The amount of log message to emit. (Default: 0)
  count: 9999999999999999999999999
  # Randomise log content (Default: true)
  randomise: true
  # The amount of log message to emit/s (Default: 1)
  eventPerSec: 1
  # The amount of bytes to emit/s  (Default: 0)
  bytePerSec: 0
  golang: false
  nginx: true
  apache: false
```
