### ISSUE TITLE
Malformed AKS (containerd) logs for Kafka output

### ISSUE THREAD

**Issue by kefiras** [kube-logging/logging-operator#1403]
**Describe the bug**:
I am trying to send the AKS pod logs to Azure Event Hub (via Kafka connector). Looking at the logs in the buffer they seem not to be properly formatted, for example:

`
time?2023-07-27T05:42:50.377810158Z?stream?stderr?logtag?F?message?I0727 05:42:50.377712       1 utils.go:211] "Skipping service due to cluster IP" service="kube-system/kubelet" clusterIP="None"?kubernetes??pod_name?kube-proxy-thzj6?namespace_name?kube-system?pod_id?$91faf430-e268-40a7-9327-103c242cfe01?labels??component?kube-proxy?controller-revision-hash?bbcd5f6f9?kubernetes.azure.com/managedby?aks?pod-template-generation?1?tier?node?host? aks-general1-11028192-vmss000004?container_name?kube-proxy?docker_id?@ddb72d7bbe07aaf4a86c246af51249f17ae79ffb4cfd293bfa6ecd24573c4e1b?container_hash?Gsha256:c46badf18d2552eb2b59291b464be70d9ef9aa9c076340c24e58f7f0fe194dfe?container_image?Cmcr.microsoft.com/oss/kubernetes/kube-proxy:v1.25.6-hotfix.20230612
`

**Expected behaviour**:
I would expect the buffer files to be in JSON format

**Steps to reproduce the bug**:
Install logging operator 4.2.2
Create clusteroutput

```
    spec:
      kafka:
        format:
          type: json
        brokers: mybroker.servicebus.windows.net:9093
        topic_key: mytopic
        default_topic: mytopic
        username:
          value: myuser
        password:
          value: mypassword
        sasl_over_ssl: false
        ssl_ca_certs_from_system: true
        ssl_verify_hostname: false
        buffer:
          retry_type: periodic
          retry_wait: 10s
          flush_mode: interval
          flush_interval: 30s
```

**Additional context**:
N/A

**Environment details**:
- Kubernetes version: v1.25.6
- Cloud-provider/provisioner: AKS
- logging-operator version: 4.2.2
- Install method : helm
- Logs from the misbehaving component (and any other relevant logs): attached
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
Config is pretty much default from helm except the Kafka clusteroutput

/kind bug
