### ISSUE TITLE
Tune syslog-ng global defaults

### ISSUE THREAD

**Issue by pepov** [kube-logging/logging-operator#1424]
The current syslog-ng defaults in the aggregator are not well adapted for the default use cases:
- be able to receive logs from hundreds of hosts
- be able to provide metrics by default without being chatty on stdout

These options should be by default:
```
spec:
  syslogng:
    maxConnections: 100
    globalOptions:
      stats:
        freq: 0
        level: 2
```
