### ISSUE TITLE
Tailer-Webhook Producing an Invalid Spec

### ISSUE THREAD

**Issue by kamirendawkins** [kube-logging/logging-operator#1444]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
After setting up the Tailer-Webhook according to the [Docs](https://kube-logging.dev/docs/configuration/extensions/tailer-webhook/#multi-container-pods), it does not seem generate a valid spec and instead produces one with duplicate volume name, mountPath, and container name. It is as though either 2 mutations occurred or the operator tried to mutate twice. I have confirmed that there is only a single operator pod, service, and  mutating webhook.

Test:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    "sidecar.logging-extensions.banzaicloud.io/tail": "/var/log/date"
spec:
  containers:
    - image: debian
      name: sample-container
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          date >> /yolo/date;
          sleep 1;
          done
```

Result:
```bash
The Pod "test-pod" is invalid:
* spec.volumes[2].name: Duplicate value: "sample-container-var-log"
* spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/var/log": must be unique
* spec.containers[2].name: Duplicate value: "sample-container-var-log-date"
```

**Expected behaviour**:
A concise description of what you expected to happen.

**Steps to reproduce the bug**:
1. Setup Prerequisites per above Docs(Cert)
2. Setup Webhook(ENV var, MutatingWebhookConfig, Service)
3. Attempt to create the example pod.

**Additional context**:
We tested this across 4 identical  clusters, all with the same results.

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.27.4
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 4.2.3
- Install method (e.g. helm or static manifests): [Operator Helm Chart](https://github.com/kube-logging/helm-charts/tree/main/charts/logging-operator) and [Logging Helm Chart](https://github.com/kube-logging/helm-charts/tree/main/charts/logging-operator-logging)
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
