### ISSUE TITLE
Flow not filtering based on label selector.

### ISSUE THREAD

**Issue by cyrus-mc** [kube-logging/logging-operator#1452]
**Describe the bug**:

I recently upgraded from 3.7 to the latest 4.3. After updating I create a simple `Flow` to validate functionality:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
  name: test
  namespace: kube-system
spec:
  match:
    - select:
        labels:
          app.kubernetes.io/name: external-dns
  globalOutputRefs:
    - opensearch
```

The rendered configuration within `FluentD` looks correct:

```
<source>
  @type forward
  @id main_forward
  bind 0.0.0.0
  port 24240
</source>
<match kubernetes.**>
  @type tag_normaliser
  @id globalFilter:0
  format ${labels.app}
</match>
<match **>
  @type label_router
  @id main
  metrics true
  <route>
    @label @3d67961aedd2b604409cfba1dc8e2c4d
    metrics_labels {"id":"flow:kube-system:test"}
    <match>
      labels app.kubernetes.io/name:external-dns
      namespaces kube-system
      negate false
    </match>
  </route>
</match>
<label @3d67961aedd2b604409cfba1dc8e2c4d>
  <match **>
    @type opensearch
    ...
  </match>
</label>
```

However what ends up happening is that all logs, from all containers get sent to the `opensearch` cluster. If I look at the buffer files in the `fluentd` container I see they grow quite large and contain messages from all containers. This is then reflected in `opensearch` when I query the data, I get back logs from all containers. 

**Expected behaviour**:

Based on the configured flow and match section I would expect that only logs from PODs with label `app.kubernetes.io/name: external-dns` would be sent to the defined output.

**Steps to reproduce the bug**:

Create logging object:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: argocd
  name: logging-server
  namespace: logging
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging
  globalFilters:
  - tag_normaliser:
      format: ${labels.app}
  fluentbit:
    HostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    filterKubernetes:
      Kubelet_Port: "10250"
      Use_Kubelet: "On"
    labels:
      app.kubernetes.io/prometheus-operated: "true"
      backstage.io/kubernetes-id: logging
    metrics:
      # handle this via our configuration
      serviceMonitor: false
    positiondb:
      hostPath:
        path: /var/cache/fluentbit
        type: DirectoryOrCreate
    podPriorityClassName: system-node-critical
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    tolerations:
    - key: kiam/nodetype
      operator: Equal
      value: server
      effect: NoSchedule
  fluentd:
    labels:
      app.kubernetes.io/prometheus-operated: "true"
      backstage.io/kubernetes-id: logging
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          volumeMode: Filesystem
          storageClassName: gp2
    metrics:
      # handle this via our configuration
      serviceMonitor: false
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 128Mi
```

Create cluster output:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: argocd
  name: opensearch
  namespace: logging
spec:
  opensearch:
    host: xxxxxxx
    port: 443
    scheme: https
    ssl_version: TLSv1_2
    index_name: dev
    buffer:
      flush_thread_count: 8
      chunk_limit_size: 1M
      total_limit_size: 5M
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
      retry_max_interval: 30s
      retry_forever: true
```

Finally create flow:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
  name: test
  namespace: kube-system
spec:
  match:
    - select:
        labels:
          app.kubernetes.io/name: external-dns
  globalOutputRefs:
    - opensearch
```

With this setup, I end up with all logs from all containers being sent to the defined output.

**Additional context**:

**Environment details**:
- Kubernetes version: EKS v1.23
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 4.3.0
- Install method (e.g. helm or static manifests): helm

/kind bug
