### ISSUE TITLE
HostTailes / fileTailers: ability to mount additional hostPaths more easily

### ISSUE THREAD

**Issue by PlayMTL** [kube-logging/logging-operator#1462]
**Is your feature request related to a problem? Please describe.**

The Rancher Kubernetes Engine (RKE) creates a directory "/var/lib/rancher/rke/log" from which log files under "/var/lib/docker/containers" are then pointed to via symlink. The Problem is, that the path /var/lib/docker/containers is not mounted, because the defined path in the fileTailers of the HostTailers is "/var/lib/rancher/rke/log". So the target file cannot be found in the fluentbit container because the host path has not been mounted.

**Describe the solution you'd like**
It would be cool if you could simply define additional "mount paths" in the fileTailers without configuring additional volume mounts.

**Describe alternatives you've considered**
My current workaround looks like this:
```
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: rke-logs
spec:
  fileTailers:
    - containerOverrides:
        volumeMounts:
          - mountPath: /var/lib/docker/containers
            name: host-docker-path
            readOnly: true
          - mountPath: /var/pos
            name: positions
          - mountPath: /var/lib/rancher/rke/log
            name: var-lib-rancher-rke-log
      name: kublet
      path: /var/lib/rancher/rke/log/kubelet_*.log
  workloadOverrides:
    volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: Directory
        name: host-docker-path
      - hostPath:
          path: /var/pos
          type: ''
        name: positions
      - hostPath:
          path: /var/lib/rancher/rke/log
          type: ''
        name: var-lib-rancher-rke-log
```

**Additional context**

Is a little bit related to: https://github.com/kube-logging/logging-operator/issues/984
