### ISSUE TITLE
Support configuration from repository in HostTailer & EventTailer without Image-Tag

### ISSUE THREAD

**Issue by PlayMTL** [kube-logging/logging-operator#1466]
**Is your feature request related to a problem? Please describe.**

If you use a private registry, you have to define the complete image (including image tag) when using EventTailer or HostTailer. It would be desirable if the user only has to define the "image-repository" and the operator automatically adds the correct image tag for the whole definition of fileTailers in the manifest. (Reference to the logging crd: spec.fluentd.image.repository)

**Describe the solution you'd like**
```
---
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: EventTailer
metadata:
  name: cluster-event-logging-kubernetes
spec:
  image: 
    repository: registry.example.com/banzaicloud/eventrouter
  controlNamespace: logging
```

**Describe alternatives you've considered**
My current implementation:
```
---
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: EventTailer
metadata:
  name: cluster-event-logging-kubernetes
spec:
  containerOverrides:
    image: registry.example.com/banzaicloud/eventrouter:v0.1.0
  controlNamespace: logging
```

**Additional context**
