### ISSUE TITLE
fluentd crashs while running with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by eumel8** [kube-logging/logging-operator#1517]
**Describe the bug**:

While running fluentd container with readOnlyRootFilesystem fluentd crashs the error `could not find a temporary directory`
This seems a known behavior on Ruby,

Ref:
- https://github.com/fluent/fluentd-kubernetes-daemonset/issues/1393
- https://github.com/kubernetes/kubernetes/issues/110835 

**Expected behaviour**:
Fluentd is running in full secure context 

**Steps to reproduce the bug**:
Apply a Logging resource with the manifest below

**Additional context**:

Workaround to running the Statefulset without Operator:

```yaml
    spec:
      initContainers:
      - args:
        - -c
        - mkdir /tmp/fluent
        - chmod +t /tmp/fluent
        command:
        - /bin/sh
        image: mtr.devops.telekom.de/kubelogging/fluentd:v1.15
        imagePullPolicy: IfNotPresent
        name: chmod-tempdirs
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      containers:
      - env:
        - name: TMPDIR
          value: /tmp/fluent
      volumes:
      - emptyDir: {}
         name: tmp
```

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.24
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Rancher RKE
- logging-operator version (e.g. 2.1.1): 4.4.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):

```
2023-10-06 16:01:02 +0000 [info]: starting fluentd-1.15.3 pid=7 ruby="2.7.8"
2023-10-06 16:01:02 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2023-10-06 16:01:02 +0000 [info]: fluent/log.rb:330:info: init supervisor logger path=nil rotate_age=nil rotate_size=nil
Unexpected error could not find a temporary directory
  /usr/lib/ruby/2.7.0/tmpdir.rb:32:in `tmpdir'
  /usr/lib/ruby/2.7.0/tmpdir.rb:108:in `tmpdir'
  /usr/lib/ruby/2.7.0/tmpdir.rb:115:in `create'
  /usr/lib/ruby/2.7.0/tmpdir.rb:83:in `mktmpdir'
  /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:47:in `before_run'
  /usr/lib/ruby/gems/2.7.0/gems/serverengine-2.3.2/lib/serverengine/server.rb:125:in `main'
  /usr/lib/ruby/gems/2.7.0/gems/serverengine-2.3.2/lib/serverengine/daemon.rb:119:in `main'
  /usr/lib/ruby/gems/2.7.0/gems/serverengine-2.3.2/lib/serverengine/daemon.rb:68:in `run'
  /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:902:in `supervise'
  /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:742:in `run_supervisor'
  /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
  /usr/bin/fluentd:23:in `load'
  /usr/bin/fluentd:23:in `<main>'
```

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: demo
  labels:
    tenant: demo
spec:
  fluentd:
    bufferVolumeImage:
      repository: mtr.devops.telekom.de/kubelogging/node-exporter
      tag: v0.6.1
    configReloaderImage:
      repository: mtr.devops.telekom.de/kubelogging/config-reloader
      tag: v0.0.5
    image:
      repository: mtr.devops.telekom.de/kubelogging/fluentd
      tag: v1.15
    logLevel: debug
    security:
      podSecurityPolicyCreate: false
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsUser: 1000
        runAsGroup: 1000
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups:
        - 1000
        runAsNonRoot: true
      roleBasedAccessControlCreate: true
  controlNamespace: demo
```

/kind bug
