### ISSUE TITLE
Slow processing of new fluentbitagent objects

### ISSUE THREAD

**Issue by jeremych1000** [kube-logging/logging-operator#1536]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
I created approx. 30x new `fluentbitagent` objects. I expected 30x fluentbit daemonsets to be created immediately by logging-operator. Instead, fluentbit daemonsets were created at approx 1 per minute, so all 30 daemonsets were only created after 30 minutes.

**Expected behaviour**:
30 fluentbit daemonsets to be created in relative quick succession (within a minute maybe?)

**Steps to reproduce the bug**:
1. Create 30x logging resources with different loggingref
1. Create 30x fluentbitagent resources with the linked loggingref
1. Observe logging-operator only creating one fluentbit daemonset per minute

**Additional context**:
- I am using logging-operator in a multi-tenant context, and have the following structure:
    - 30x tenants, with a dedicated fluentbit/fluentd per tenant consisting of the following
        - 1x logging resource per tenant with 1x fluentd defined (statefulset)
        - 1x fluentbitagent resource per tenant
        - 1x clusterflow per tenant
        - 1x clusteroutput per tenant
- See screenshots showing `fluentbitagent` resources created at the same time, but fluentbit daemonsets being created at a staggered pace.
- Restarting the logging-operator had no effect.
- Fluentd was absolutely fine.
- CPU/RAM normal

![image](https://github.com/kube-logging/logging-operator/assets/17688104/cb4d7f83-4d4b-44f7-890c-604cd540e2a8)
![image](https://github.com/kube-logging/logging-operator/assets/17688104/390a56c2-2a1d-4181-a0be-f83ff59ccee0)
![image](https://github.com/kube-logging/logging-operator/assets/17688104/a84f5e08-72b9-4adf-b671-b878f29a145d)

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.27
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS EKS
- logging-operator version (e.g. 2.1.1): 4.4.1-rc0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): Normal logs, but could only see the fluentbitagent reconciler log only once every minute
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: ..

/kind bug

**Comment by pepov** [comment]
We need to check this as this might have already been solved with removing the 1minute retry after configcheck that intermittently caused delays in the reconciliation.

**Comment by kristofgyuracz** [comment]
Tried reproducing with LO 4.3.0 and 4.6.0 to check if this change fixed the issue:
https://github.com/kube-logging/logging-operator/commit/7fe3a8248209fa5d23aca9c4b865353790148b15

Deployed 10 LO deployments with the following script, wasn't able to reproduce neither on 4.3 nor on 4.6:
```
for NUM in {1..10}
do
    kubectl apply -f - <<- EOF
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
    name: all-to-file-${NUM}
spec:
    fluentd: {}
    controlNamespace: default
    loggingRef: all-to-file-${NUM}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
    name: all-to-file-${NUM}
spec:
    loggingRef: all-to-file-${NUM}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
    name: all-${NUM}
spec:
    loggingRef: all-to-file-${NUM}
    localOutputRefs:
        - nullout-${NUM}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
    name: nullout-${NUM}
spec:
    loggingRef: all-to-file-${NUM}
    nullout: {}
EOF
done
```
