### ISSUE TITLE
Create e2e test for config checks

### ISSUE THREAD

**Issue by pepov** [kube-logging/logging-operator#1540]
Config check failure on fluentd creating a file output with an invalid pattern:
```
spec:
  file:
    append: true
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 10s
    path: /tmp/logs/asd
```

Output
```
2023-10-16 13:59:22 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Parameter 'path: /tmp/logs/asd.%Y%m%d%H%M.log' doesn't have tag placeholder"
```

Test scenario to implement:
- Creating a valid configuration succeeds and writes result into the logging resource status.
- Updating to an invalid configuration modifies the status with a failed result.
- Reverting back get passed the configcheck.

TODO
- [ ] define example for syslog-ng as well
