### ISSUE TITLE
enabling fluentd AND fluentbit metrics at the same doesn't work

### ISSUE THREAD

**Issue by xinity** [kube-logging/logging-operator#1573]
**Describe the bug**:
I've followed the documentation about monitoring the logging pipelines: https://kube-logging.dev/docs/operation/logging-operator-monitoring/

and i'm able to have both fluentd and fluentbit metrics enabled

**Expected behaviour**:
I should see when doing : `kubectl get svc -n logging`
fluentd-metrics svc AND fluentbit-metrics svc

**Steps to reproduce the bug**:
apply this logging definition:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: gke-dev-logging
spec:
  controlNamespace: logging
  fluentd:
    disablePvc: true
    metrics:
      serviceMonitor: true
  fluentbit:
    metrics:
      serviceMonitor: true
```

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.26.6-gke.1700
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GKE
- logging-operator version (e.g. 2.1.1): 4.4.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): 
```
{"level":"error","ts":"2023-11-02T17:36:30Z","msg":"Reconciler error","controller":"logging","controllerGroup":"logging.banzaicloud.io","controllerKind":"Logging","Logging":{"name":"gke-dev-logging"},"namespace":"","name":"gke-dev-logging","reconcileID":"70cf5078-959c-466a-ac2d-017ac1f4a0eb","error":"fluentbit has to be removed from the logging resource before the new FluentbitAgent can be reconciled","errorVerbose":"fluentbit has to be removed from the logging resource before the new FluentbitAgent can be reconciled\ngithub.com/kube-logging/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/usr/local/src/logging-operator/controllers/logging/logging_controller.go:227\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
````

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: gke-dev-logging
spec:
  controlNamespace: logging
  fluentd:
    disablePvc: true
    metrics:
      serviceMonitor: true
  fluentbit:
    metrics:
      serviceMonitor: true
```

/kind bug

**Comment by xinity** [comment]
issue fixed thanks to @pepov advices on discord :)

here's the final correctly working configuration:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: gke-dev-logging
spec:
  controlNamespace: logging
  fluentd:
    disablePvc: true
    metrics:
      serviceMonitor: true
```

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
    name: gke-dev-fluentdbit
spec:
  metrics:
    serviceMonitor: true
```
