### ISSUE TITLE
External aggregator configuration

### ISSUE THREAD

**Issue by pepov** [kube-logging/logging-operator#1574]
## Problem statement

We want to allow fluentd/syslog-ng to be created in a user namespace without the user being able to configure other aspects of the logging domain. To do this, introduce a separate CRD to allow the configuration of fluentd/syslogng resources.

## Requirements
- both methods should continue to work (either embedded or external, although not both at the same time)
- migration path should be trivial, without changing anything in underlying resources

## Questions
- does it make sense to allow multiple fluentd resources for the same logging? -> no, for now only one config will be considered for inclusion
- should the new fluentd/syslogng CRD be cluster or namespace scoped? -> it will be namespace scoped to allow for a simpler RBAC setup
- how to handle loggingRefs? -> logging refs are out of scope, the external configuration will be found based on the control namespace implicitly

## Approach
Extend the logging resource with a configuration that allows to reference a namespaced fluentd/syslogng resource in the user's namespace. The logging operator will then use that external resource spec instead of the embedded one to create downstream resources.

```
kind: Logging
metadata:
  name: asd
spec:
  fluentd: {}                                <--- this is not going to be applied, as the operator will discover the external config
  controlNamespace: control
---
kind: FluentdConfig
metadata:
  name: asd-fluentd
  namespace: control               <--- must be in the "control" namespace
spec:
  actualConfig: {}                      <--- this is going to applied
```

### Caveats

- If there are multiple external config resources, only the first will be applied (others will receive an error in their status) 
- Logging refs won't be part of the fluentd/syslogng resource in this case, we are simply looking up resources in the control namespace. 

## Notes
- defaulting can be tricky to implement, as it only applies to the logging resource's spec.fluentd, but we want that to be applied to the detached fluentd resource as well.
- the logging controller should update the fluentd/syslogng resource status with:
  - logging resource name
  - whether it succeeded or failed to be applied?
- the logging resource status should also be updated with the information that an external configuration is being used
