### ISSUE TITLE
eventTailer: Missing documented EventTailerSpec image (*tailer.ImageSpec, optional)

### ISSUE THREAD

**Issue by pbdger** [kube-logging/logging-operator#1654]
In the latest documentation of the eventtailer (https://kube-logging.dev/docs/configuration/crds/extensions/eventtailer_types/) you find the specs to define image specs.

**Expected behaviour**:

The CRD of the eventtailer should contain the image specs, e.g.

```
spec:
  controlNamespace: logging
  image:
    pullPolicy: Always
    repository: myownrepo/kube-logging/eventrouter
    tag: v0.1.0
```

A concise description of what you expected to happen.

**Steps to reproduce the bug**:

Add the spec as shown above in the values.yaml of the Helm chart.

**Environment details**:
- logging-operator version: 4.5.1

**Bug**:
The CRD contains no image spec information.

**Comment by OverOrion** [comment]
Hey @pbdger, the CRD for the EventTailer seems to contain image specs:
https://github.com/kube-logging/logging-operator/blob/e87e3e2df4f422be21f00360de6d45e9ffb29cfa/charts/logging-operator/crds/logging-extensions.banzaicloud.io_eventtailers.yaml#L314

Could you share your yaml config used?

**Comment by pbdger** [comment]
We set the values for Helm chart via Flux. The code looks like 

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: myhelmrepository
        namespace: mynamespace
      chart: logging-operator
      version: "4.5.1"
      interval: 10m
  values:
    logging:
      enabled: true
      fluentbit:
        image:
          repository: myrepo/fluent/fluent-bit
      eventTailer:
        image:
          repository: my/kube-logging/eventrouter
          tag: "v0.1.0"
          pullPolicy: "Always"
        workloadMetaOverrides:
          labels:
            "gnp.phoenix.local/k8s-api-access": "read-events"

```


The outcome of the generated CRD contains for EventTailerSpec the workloadMetaOverrides specs but no data for image specs. 

The CRD looks like

```
...
spec:
  controlNamespace: logging
  workloadMetaOverrides:
    labels:
      gnp.phoenix.local/k8s-api-access: read-events
```

So the image specs are not crested via logging operator the the event trailer CRD.
