### ISSUE TITLE
Unable to add enhanceK8s global filter the config process is unable to connect to the kubernetes api

### ISSUE THREAD

**Issue by pepov** [kube-logging/logging-operator#1659]
### Discussed in https://github.com/orgs/kube-logging/discussions/1658

<div type='discussions-op-text'>

<sup>Originally posted by **vipinjn24** January 31, 2024</sup>
Hi,

I am trying to add enhanceK8s global, but it seems the config job fails to connect to the cluster.

My config

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: fluentd-resource
  namespace: logging
spec:
  controlNamespace: logging
  # globalFilters:
  #   - enhanceK8s:
  #       kubernetes_url: "https://kubernetes.default.svc.cluster.local"
  #       verify_ssl: false
  fluentd:
    disablePvc: true
```

I there is a specific requirements let me know.
I am using bare metal kubeadm cluster.</div>
