### ISSUE TITLE
Hosttailer + eventtailer doesn't support defining resources

### ISSUE THREAD

**Issue by jeremych1000** [kube-logging/logging-operator#1736]
**Describe the bug**:
I can't define requests and limits for hostrailer and eventtailer. We run Kyverno which forces every pod to have resources defined.

**Expected behaviour**:
There is a resources block in the CR.

**Steps to reproduce the bug**:
`error building typed value from config resource: .spec.resources: field not declared in schema`

**Additional context**:
https://kube-logging.dev/docs/configuration/crds/extensions/hosttailer_types/

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.28.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): on prem
- logging-operator version (e.g. 2.1.1): 4.6.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): `error building typed value from config resource: .spec.resources: field not declared in schema`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
in `logging`
```
  # -- HostTailer config
  hostTailer: 
    name: hosttailer
    # fileTailers:
    #   - name: sample-file
    #     path: /var/log/sample-file
    #     disabled: false
    systemdTailers:
      - name: system-sample
        disabled: false
        maxEntries: 20
        systemdFilter: kubelet.service


  # -- EventTailer config
  eventTailer: 
    name: eventtailer
    image:
      repository: "<..>/kube-logging/eventrouter"
      tag: "0.4.0"
      pullPolicy: IfNotPresent
      imagePullSecrets: []
    pvc:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
    storage: 1Gi
    storageClassName: standard
```
/kind bug
