### ISSUE TITLE
Upgrade fluent-bit to fix CVE-2024-4323 / GHSA-5rjf-prwh-pp7q

### ISSUE THREAD

**Issue by smlx** [kube-logging/logging-operator#1741]
**Describe the bug**:
There is a [recently disclosed security vulnerability](https://www.tenable.com/security/research/tra-2024-17) in fluent-bit versions v2.0.7-v3.0.3 inclusive. It is patched in v3.0.4.

**Expected behaviour**:
I would expect the logging-operator to use a patched version of fluent-bit.

**Steps to reproduce the bug**:
See that the logging-operator [uses fluent-bit v2.2.2](https://github.com/kube-logging/logging-operator/blob/017e076cc5a1d673dfed7b4792ad638fdde4bf14/pkg/sdk/logging/api/v1beta1/logging_types.go#L167).

**Additional context**:
Unfortunately the GHSA for this issue is not yet public so this link 404s for me: [link](https://github.com/advisories/GHSA-5rjf-prwh-pp7q). I assume it will be made public shortly.

**Environment details**:
n/a

/kind bug

**Comment by kefiras** [comment]
+1

**Comment by pepov** [comment]
I'm upgrading fluentbit in the latest release now and in mainline, please set the fluentbit version in your Logging or FluentbitAgent resource manually:
```
kind: Logging
spec:
  fluentbit:
    image:
      tag: "3.0.4"
```

```
kind: FluentbitAgent
spec:
  image:
    tag: "3.0.4"
```
