### ISSUE TITLE
Make severity configurable in PrometheusRules

### ISSUE THREAD

**Issue by sebastiangaiser** [kube-logging/logging-operator#1749]
**Is your feature request related to a problem? Please describe.**
Currently the severity is hardcoded in the PrometheusRules like [here](https://github.com/kube-logging/logging-operator/blob/a71e24e740c893c92c364064647e5bf9070f2aa8/pkg/resources/fluentd/prometheusrules.go#L47)

**Describe the solution you'd like**
It would be great to have them configurable via the Logging CR e.g.:

```
spec:
  fluentd:
    metrics:
      prometheusRules: true
      severity: my-custom-severity
  fluentbit:
    metrics:
      prometheusRules: true
      severity: my-custom-severity
  syslogNG:
    metrics:
      prometheusRules: true
      severity: my-custom-severity
```

**Describe alternatives you've considered**
My current workaround is to disable the PrometheusRules and deploy them in the way I want

**Additional context**
Logging Operator docs: https://kube-logging.dev/docs/operation/alerting/

**Comment by sebastiangaiser** [comment]
@pepov sorry to ping you but could you please mind have a look :D

**Comment by pepov** [comment]
Good idea, but I don't have any free cycles currently. We are looking for contributors to take on "good first issues" like this!

**Comment by aditya7302** [comment]
I would like to work on this issue. Can you assign it to me ?

**Comment by pepov** [comment]
@aditya7302 sure, thanks!

**Comment by aditya7302** [comment]
@pepov is this [file](https://github.com/kube-logging/logging-operator/blob/a71e24e740c893c92c364064647e5bf9070f2aa8/config/crd/bases/logging.banzaicloud.io_loggings.yaml) is where severity metric should be added to make it configurable ?

**Comment by sebastiangaiser** [comment]
@pepov @aditya7302 maybe my comment now is a bit controversial to remove the PrometheusRules completely or making the whole [Rules block configurable](https://github.com/kube-logging/logging-operator/blob/3c20c69c03f588a629b89e92f1b871ebb8e77038/pkg/resources/fluentbit/buffervolumeprometheusrules.go#L40)

**Comment by pepov** [comment]
I would add a list based override option that would allow setting overrides for the rules based on the list index. Also we could define a type that would allow overriding other fields as well for the rule.

For example the below metrics config would keep the first rule unmodified but would change a few properties of the second rule.
```
    metrics:
      prometheusRules: true
      prometheusRuleOverrides: 
        - {}
        - for: 1m
          labels:
             severity: warning
             additionalLabel: b
```

I think we could also allow a list item to be removed if we set the corresponding item to nil.
