### ISSUE TITLE
configHotReload of FluentbitAgent ignores imagePullSecrets

### ISSUE THREAD

**Issue by sebhoss** [kube-logging/logging-operator#1771]
**Describe the bug**:

I created a `FluentbitAgent` like this:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: default
  namespace: logging
spec:
  configHotReload:
    image:
      imagePullSecrets:
        - name: some-pull-secret
      repository: internal.registry.example/ghcr/kube-logging/config-reloader
```

The configured pull secret was not part of the pod spec for fluentbit and thus the config-reloader image could not be pulled.

**Expected behaviour**:

I expected that the configured pull secret appears as part of the pod spec for fluentbit pods and that the config-reloader image is pulled through our internal image registry.

**Steps to reproduce the bug**:

- Apply `FluentbitAgent` with `configHotReload` using at least one `image.imagePullSecrets`
- Look at spec of running fluentbit pods whether the pull secret appears

**Additional context**:

none

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.29
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kubeadm
- logging-operator version (e.g. 2.1.1): 4.8.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): none
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: see above

/kind bug
