### ISSUE TITLE
ClusterFlow exclude logs feature is not working properly

### ISSUE THREAD

**Issue by sjanorkar** [kube-logging/logging-operator#1783]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
ClusterFlow exclude logs feature is not working properly. Even after excluding the logs with the help of labels, container names I can see the logs pushed to the output. 

**Expected behaviour**:
All the labels, namespaces and container_names mentioned in match.exclude[] should not be present in the log destination 

**Steps to reproduce the bug**:
Use default logging Operator config.

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: aicore-logs-flow
  namespace: logging
spec:
  filters:
    - tag_normaliser: {}
    - record_transformer:
        enable_ruby: true
        records:
          - namespace: ${record["kubernetes"]["namespace_name"]}
          - app: ${record["kubernetes"]["labels"]["app"]}
          - cluster_name: {{ .Values.environmentName }}
          - container: ${record["kubernetes"]["container_name"]}
          - pod: ${record["kubernetes"]["pod_name"]}
          - node_name: ${record["kubernetes"]["host"]}
          - ai_sap_com_tenantId: aicore
        remove_keys: kubernetes
  match:
    - exclude:
        labels:
          app: kubernetes # apiserver-proxy, kube-proxy-aalpha-worker, kube-proxy-loki, kube-proxy-node, kube-proxy-prometheus
    - exclude:
        container_names:
          - nginx
          - kube-proxy
    - exclude:
        labels:
          app: <label>
    - exclude:
        labels:
          app: <label>
    - exclude:
        labels: 
          k8s-app: <label>
    - exclude:
        namespaces:
          - prometheus
          - default 
          - tests
  globalOutputRefs:
    -logs-output
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
