### ISSUE TITLE
make it easier to change the repository for syslog images

### ISSUE THREAD

**Issue by sebhoss** [kube-logging/logging-operator#1796]
**Is your feature request related to a problem? Please describe.**

We want to pull all container images through our internal registry. Currently, we can only do this for the syslog statefulset by specifying the container images ourselves like this:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGConfig
metadata:
  name: default
  namespace: logging
spec:
  statefulSet:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: pull-secret
          containers:
            - name: syslog-ng
              image: example.com/ghcr/axoflow/axosyslog:4.8.0
            - name: config-reloader
              image: example.com/ghcr/kube-logging/syslogng-reload:v1.3.1
```
 
I think this is bad because I now have to manage the version of those images instead of letting the operator handle that and I need to verify on each operator update that those container names still remained the same or otherwise risk a misconfiguration.

**Describe the solution you'd like**

I would love to do something similar to what is possible with the FluentbitAgent resource:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGConfig
metadata:
  name: default
  namespace: logging
spec:
  image:
    registry: example.com/ghcr
    imagePullSecrets:
      - name: pull-secret
```

Note that I have used `registry` here instead of `repository` which is used in FluentbitAgent. The idea here is that the final image location is `<registry>/<repository>:<tag>`

**Describe alternatives you've considered**

Just configure the STS as in the top example.

**Additional context**
