### ISSUE TITLE
FluentD buffer pvc annotations and labels

### ISSUE THREAD

**Issue by sebastiangaiser** [kube-logging/logging-operator#1819]
**Is your feature request related to a problem? Please describe.**
Hey, we were looking for the possibility to configure labels and annotations for the Fluentd PersistentVolumeClaim's which seams to be not possible according to the docs: https://kube-logging.dev/4.0/docs/logging-infrastructure/fluentd/?highlight=persistentvol#persistent-volume-claim
My use-case would be excluding from alerting using kube-prometheus-stack: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/config.libsonnet#L118

**Describe the solution you'd like**
Extend the logging crd for pvc labels and annotations, e.g.:

```
spec:
  fluentd:
    bufferStorageVolume:
      pvc:
        labels: {}
        annotations: {}
```

**Describe alternatives you've considered**
Currently we work around this via Kyverno Policy.

**Additional context**
---
