### ISSUE TITLE
Fluentd `prometheusRulesOverride` only work for the last override (last object in array)

### ISSUE THREAD

**Issue by R-Studio** [kube-logging/logging-operator#1842]
**Describe the bug**:
Fluentd `prometheusRulesOverride` only work for the last object in array. So if you want to override multiple alerts, only the last in the array get applied.

Example I have the following two overrides in the custom resource `Logging`, only the override for `FluentdOutputError` is working. `FluentdRetry` will be ignored:

```yaml
spec:
  fluentd:
    metrics:
      prometheusRules: true
      prometheusRulesOverride:
        - alert: FluentdRetry
          expr: >-
            increase(fluentd_status_retry_count{job="logging-operator-ops-fluentd-metrics",
            namespace="logging-operator-te"}[10m]) > 10
        - alert: FluentdOutputError
          expr: >-
            increase(fluentd_output_status_num_errors{job="logging-operator-ops-fluentd-metrics",
            namespace="logging-operator-te"}[10m]) > 5
```

**Expected behaviour**:
Every override should work.

**Steps to reproduce the bug**:
- Deploy the Logging Operator v4.9.1
- Enable `PrometheusRules` 
- Override multiple `PrometheusRules` for the fluentd component

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.27
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): OpenShift 4.14
- logging-operator version (e.g. 2.1.1): 4.9.1
- Install method (e.g. helm or static manifests): helm

/kind bug
