### ISSUE TITLE
fluentd-metrics service should be headless

### ISSUE THREAD

**Issue by karloramone** [kube-logging/logging-operator#1850]
**Describe the bug**:
Currently the operator creates a `fluentd-metrics` service as of type: ClusterIP with assigned IP. 
If you enable serviceMonitor in `logging.spec.fluentd.serviceMonitor` it will be configured to use this `fluentd-metrics` as a target. 
In case you specify multiple replica Fluentd StatefulSet each of those process different chunks received from the FluentBit through the `fluentd` service in front.
Therefore, each replica creates and exposes different metrics.

**Expected behaviour**:
`fluentd-metrics` service should be headless so serviceMonitor points to each of those replicas.

/kind bug

**Comment by csatib02** [comment]
Hi @karloramone,

I started reproducing what you covered in your ticket:
- I first verified that all of our exposed metrics services are already configured as headless. This aligns with the expected behavior, ensuring that ServiceMonitor can point to each Fluentd replica individually.
- Applied this configuration and enabled metrics collection by installing a Prometheus-operator.

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-example
spec:
  controlNamespace: logging
  enableRecreateWorkloadOnImmutableFieldChange: true
  fluentd:
    bufferVolumeMetrics: 
      serviceMonitor: true
    metrics: 
      serviceMonitor: true
    scaling:
      replicas: 2
  fluentbit:
    metrics:
      serviceMonitor: true
    bufferVolumeMetrics: 
      serviceMonitor: true
```
- The ServiceMonitor correctly targets the headless Fluentd-metrics service and fetches metrics individually for each replica.

![Image](https://github.com/user-attachments/assets/48661efa-aea7-456c-a8a2-83921fd1c853)


- Each `Fluentd` replica exposes its own set of metrics (as shown in the attached screenshot). Metrics like `fluent_output_status_emit_count` are properly segregated per replica, with values corresponding to different pods.

![Image](https://github.com/user-attachments/assets/c625fe15-caef-4a30-b545-fd506a97f8aa)

This behavior is consistent with the expected functionality.
