### ISSUE TITLE
Multiple Logging resources

### ISSUE THREAD

**Issue by sagarun** [kube-logging/logging-operator#1901]
**Describe the bug**:
Two "Logging" resources created not sure why. 

```
 k get logging                                                                                                                                                                                
NAME               LOGGINGREF   CONTROLNAMESPACE        WATCHNAMESPACES   PROBLEMS
fluentd-volume                  sulu-logging-operator
logging-operator                sulu-logging-operator
```

This is part of my values.yaml
```
logging:
  enabled: true
  fluentbitDisabled: false
  fluentdDisabled: false
  name: sulu-logging
  namespace: sulu-logging-operator

  fluentbit:
    extraVolumeMounts:
    - destination: /run/log/journal
      readOnly: true
      source: /run/log/journal
    - destination: /etc/machine-id
      readOnly: true
      source: /etc/machine-id
    - destination: /var/log/pods # This is where containerd logs are stored.
      readOnly: true
      source: /var/log/pods
    customConfigSecret: custom-fluentbit-config
    metrics:
      port: 2020
      prometheusAnnotations: false
      serviceMonitor: true
    labels:
      prometheus: sulu
    image:
      repository: <private-registry>/fluent/fluent-bit
      tag: "3.1.8"
      pullPolicy: IfNotPresent
    podPriorityClassName: "system-node-critical"
  fluentd:
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              type: local
          storageClassName: manual
          volumeMode: Filesystem
    port: 24240
    metrics:
      port: 9880
      prometheusAnnotations: false
      serviceMonitor: true
    labels:
      prometheus: sulu
    resources:
      requests:
        cpu: 1000m
        memory: 1024M
      limits:
        cpu: 2000m
        memory: 2048M
    image:
      repository: <private-registry>/kube-logging/fluentd
      tag: "v1.16-4.11-full"
      pullPolicy: IfNotPresent
    configReloaderImage:
      repository: <private-registry>/ghcr.io/kube-logging/config-reloader
      tag: "v0.0.6"
      pullPolicy: IfNotPresent
    workers: 4
```

I did define a PV using this yaml:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-operator
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/fluentd-buffer"
```

The fluentd-volume logging resource got assigned the above PV but it seems to be pulling images from external registry, even though values.yaml asks it to pull from private docker registry.

The `logging-operator` logging resource stuck waiting on a PV.

**Expected behaviour**:
Just one "kind: Logging" resource is created by logging-operator.  Perhaps i am doing something wrong. I am completely new to logging-operator.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (v1.28.8)
- Cloud-provider/provisioner: 
- logging-operator version: 4.11.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
```{"level":"error","ts":"2025-01-04T08:41:15Z","msg":"Reconciler error","controller":"logging","controllerGroup":"logging.banzaicloud.io","controllerKind":"Logging","Logging":{"name":"logging-operator"},"namespace":"","name":"logging-operator","reconcileID":"aad5cc2f-6cbd-4eaa-a9ef-251196f24cfd","error":"failed to reconcile resource: Object has to be recreated, but refusing to remove without explicitly being told so. Use logging.spec.enableRecreateWorkloadOnImmutableFieldChange to move on but make sure to understand the consequences. As of fluentd, to avoid data loss, make sure to use a persistent volume for buffers, which is the default, unless explicitly disabled or configured differently. As of fluent-bit, to avoid duplicated logs, make sure to configure a hostPath volume for the positions through `logging.spec.fluentbit.spec.positiondb`. : DaemonSet.apps \"logging-operator-fluentbit\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app.kubernetes.io/instance\":\"logging-operator\", \"app.kubernetes.io/managed-by\":\"logging-operator\", \"app.kubernetes.io/name\":\"fluentbit\", \"prometheus\":\"sulu\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable","errorVerbose":"DaemonSet.apps \"logging-operator-fluentbit\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app.kubernetes.io/instance\":\"logging-operator\", \"app.kubernetes.io/managed-by\":\"logging-operator\", \"app.kubernetes.io/name\":\"fluentbit\", \"prometheus\":\"sulu\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable\nObject has to be recreated, but refusing to remove without explicitly being told so. Use logging.spec.enableRecreateWorkloadOnImmutableFieldChange to move on but make sure to understand the consequences. As of fluentd, to avoid data loss, make sure to use a persistent volume for buffers, which is the default, unless explicitly disabled or configured differently. As of fluent-bit, to avoid duplicated logs, make sure to configure a hostPath volume for the positions through `logging.spec.fluentbit.spec.positiondb`. \ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.37.0/pkg/reconciler/resource.go:515\ngithub.com/kube-logging/logging-operator/pkg/resources/fluentbit.(*Reconciler).Reconcile\n\t/usr/local/src/logging-operator/pkg/resources/fluentbit/fluentbit.go:154\ngithub.com/kube-logging/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/usr/local/src/logging-operator/controllers/logging/logging_controller.go:304\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\nfailed to reconcile resource\ngithub.com/kube-logging/logging-operator/pkg/resources/fluentbit.(*Reconciler).Reconcile\n\t/usr/local/src/logging-operator/pkg/resources/fluentbit/fluentbit.go:156\ngithub.com/kube-logging/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/usr/local/src/logging-operator/controllers/logging/logging_controller.go:304\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}```

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
