### ISSUE TITLE
Support multiple HostTailers in the chart

### ISSUE THREAD

**Issue by pepov** [kube-logging/logging-operator#1909]
The helm chart currently only supports defining a single host tailer, but there are situations where more than one need to be defined, for example when different host tailers need to be deployed to different set of nodes using nodeselectors.

Example:
```
hostTailer:
  enabled: true
  - name: kubeauditane                                 # <--------- currently this is not a list  
    workloadOverrides:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    fileTailers:
      - name: kube-audit
        path: /var/lib/rancher/rke2/server/logs/*.log
  
  - name: workersnodesonly
    workloadOverrides:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    fileTailers:
      - name: kube-audit
        path: /var/lib/rancher/rke2/agent/logs/*.log
```
