### ISSUE TITLE
Make buffer volume metrics PrometheusRules configurable

### ISSUE THREAD

**Issue by sebastiangaiser** [kube-logging/logging-operator#1928]
**Is your feature request related to a problem? Please describe.**
In https://github.com/kube-logging/logging-operator/pull/1790 `PrometheusRule` overrides were introduced. Unfortunately only for FluentD/Fluent-bit metrics and not for buffer volume metrics.

**Describe the solution you'd like**
Please add the same overrides for the buffer volume metrics, e.g.:
```
fluentd:
  bufferVolumeMetrics:
    prometheusRules: true
    prometheusRulesOverride:
    - alert: FluentbitBufferSize
      labels:
         severity:  warning # former 'critical'
fluentd:
  bufferVolumeMetrics:
    prometheusRules: true
    prometheusRulesOverride:
    - alert: FluentdPredictedBufferGrowth
      expr: ...
syslogng:
  bufferVolumeMetrics:
    prometheusRules: true
    prometheusRulesOverride:
    ...
```

**Describe alternatives you've considered**
Disable `prometheusRules` and deploy them separately.

**Additional context**
---
