### ISSUE TITLE
FluentbitAgent: configuring filterKubernete.K8S-Logging.Parser should enable inputTail.multiline.parser

### ISSUE THREAD

**Issue by baby-gnu** [kube-logging/logging-operator#1956]
**Is your feature request related to a problem? Please describe.**

It took times to have a working setup with [kubernetes pod annotation](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-pod-annotations).

**Describe the solution you'd like**

When [`filterKubernete.K8S-Logging.Parser`](https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentbit_types/#filterkubernetes-k8s-logging.parser) is enabled, the [`inputTail.multiline.parser`](https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentbit_types/#inputtail-multiline.parser) is automatically enabled too.

**Describe alternatives you've considered**

Add a note in [documentation](https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentbit_types/#filterkubernetes-k8s-logging.parser) explicitly describing the mandatory dependency. 

**Additional context**

I initially opened [an issue is fluent-bit](https://github.com/fluent/fluent-bit/issues/9943) and finally found the solution: I had to manually configure [`inputTail.multiline.parser`](https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentbit_types/#inputtail-multiline.parser)

Thanks.

**Comment by pepov** [comment]
@baby-gnu thanks for the report! Can you add your working configuration snippet here as the example we should provide?

**Comment by baby-gnu** [comment]
Hello

Here is my working configuration:

- `inputTail.multiline.parser`: make `filterKubernetes.K8S-Logging.Parser: "On"` really works
- `Merge_Log_Key: "parsed"`: is optional but adding keys at top level is risky because it can result in conflicting keys (for example the `host` from `k8s-nginx-ingress` conflicting with the kubernetes `host`)

``` yaml
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: example-fluentbit
spec:
  metrics:
    serviceMonitor: true
  inputTail:
    multiline.parser: [cri]
  filterKubernetes:
    K8S-Logging.Parser: "On"
    Merge_Log_Key: "parsed"
...
```
