### ISSUE TITLE
Override of Hosttailer default image fails

### ISSUE THREAD

**Issue by diogoasouza** [kube-logging/logging-operator#2016]
**Describe the bug**:
Hosttailer ignores the image set in `spec.image.repository`, it only works when you set `containerOverrides.image` for each `fileTrailers`.

**Expected behaviour**:
When setting `spec.image.repository`, Hosttailer should use that image in all containers if no `containerOverrides` is set, like `EventTailer` does.

**Steps to reproduce the bug**:
1. Create a new HostTailer resource populating `spec.image`
```yaml
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata: 
  name: cluster-system-log-test
spec: 
  image: 
    repository: docker-kube-registry.fake/fluent/fluent-bit
    tag: 3.1.8
  workloadMetaOverrides: 
    annotations: {}
    labels: {}
  fileTailers: 
    - disabled: false
      name: kubelet-log
      path: /var/lib/rancher/rke2/agent/logs/*.log
    - disabled: false
      name: containerd-log
      path: /var/lib/rancher/rke2/agent/containerd/*.log
    - name: kube-audit
      path: /var/log/kube-audit/audit-log.json
      disabled: false
```
2. Check the daemonSet created and look at the images used by each container

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.31
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): K3s
- logging-operator version (e.g. 2.1.1): 5.2
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment]
I beleive this was a mistake in the original PR. Based on the code this should work for both file and systemd tailers:
```
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata: 
  name: cluster-system-log-test
spec: 
  workloadMetaOverrides: 
    annotations: {}
    labels: {}
  fileTailers: 
    - disabled: false
      name: kubelet-log
      path: /var/lib/rancher/rke2/agent/logs/*.log
      image: 
        repository: docker-kube-registry.fake/fluent/fluent-bit
        tag: 3.1.8
```
