### ISSUE TITLE
Fluentd configuration is formed incorrectly when using rdkafka_options in ClusterOutput/Output

### ISSUE THREAD

**Issue by verdel** [kube-logging/logging-operator#2017]
**Describe the bug**:

In Pull Request #1875, the ability to pass fine-tuning parameters for librdkafka was added when using the rdkafka2 output plugin to send events to Kafka.

In issue #1874, which was opened before the creation of the Pull Request, the Fluentd configuration format is shown, indicating that `rdkafka_options` is a parameter of type hash (like headers), and not a section, like buffer or format.

```
@type rdkafka2
   enable_ruby
   brokers "<broker>"
   get_kafka_client_log true
   default_topic custom
   use_event_time true
   username "#{ENV["nonprd_ULFF_KAFKA_USER"]}"
   password "#{ENV["nonprd_ULFF_KAFKA_PASS"]}"
   rdkafka_options {
     "log_level":6,
     "sasl.mechanism": "SCRAM-SHA-512",
     "security.protocol": "sasl_ssl"
   }
```

This can also be seen in the source code of the [fluent-plugin-kafka](https://github.com/fluent/fluent-plugin-kafka/blob/bf60694c95bca6a5f2342bb314e688f0271feeda/lib/fluent/plugin/out_rdkafka2.rb#L93).

```ruby
config_param :rdkafka_options, :hash, :default => {}, :desc => 'Set any rdkafka configuration. See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md'

config_section :buffer do
  config_set_default :chunk_keys, ["topic"]
end
config_section :format do
  config_set_default :@type, 'json'
  config_set_default :add_newline, false
end
```

Currently, in the generated configuration file, the values from the `rdkafka_options` parameter are incorrectly placed in a section:

```
<match **>
    @type rdkafka2
    @id test
    brokers kafka-headless.kafka.svc.cluster.local:29092
    default_topic topic
    ssl_verify_hostname false
    <buffer tag,time>
      @type file
      path /buffers/test.*.buffer
      retry_forever true
      timekey 1m
      timekey_use_utc true
      timekey_wait 30s
    </buffer>
    <rdkafka_options>
      sasl.mechanisms PLAIN
      sasl.username user
      security.protocol SASL_SSL
      ssl.ca.location /etc/ssl/certs/ca-certificates.crt
      ssl.certificate.location /etc/ssl/certs/tls.crt
      ssl.key.location /etc/ssl/certs/tls.key
      ssl.key.password password
    </rdkafka_options>
    <format>
      @type json
    </format>
</match>
```

In the Kubernetes cluster, inside the pod `logging-operator-fluentd-configcheck`, which is created after modifying the `ClusterOutput`/`Output` custom resources and performs a dry-run check of the updated configuration, the following warning message can be seen:

```
2025-04-17 16:12:17 +0000 [warn]: section <rdkafka_options> is not used in <store> of rdkafka2 plugin
```

**Expected behaviour**:

When the `rdkafka_options` parameter and `use_rdkafka: true` are added to a `ClusterOutput` or `Output` custom resource, the Fluentd configuration file will be generated correctly, allowing fine-tuning of `librdkafka` parameters.

**Steps to reproduce the bug**:
1. Create custom resource `ClusterOutput`

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  annotations:
  labels:
  name: opensearch
  namespace: logging-system
spec:
  kafka:
    brokers: <kafka_broker_address>
    buffer:
      chunk_limit_size: "1000000"
      disable_chunk_backup: true
      flush_interval: 1s
      flush_mode: interval
      flush_thread_count: 2
      overflow_action: drop_oldest_chunk
      retry_forever: false
      retry_max_interval: "30"
      retry_timeout: 1h
      retry_type: exponential_backoff
      tags: $.kubernetes.namespace_name
      timekey: 10s
      timekey_use_utc: true
      timekey_wait: 1s
      type: file
    default_topic: default
    format:
      type: json
    rdkafka_options:
      message.max.bytes: 1000000
    topic_key: $.kubernetes.namespace_name
    use_rdkafka: true
```
2. View logs from `logging-operator-fluentd-configcheck` pod

```
2025-04-17 16:12:17 +0000 [warn]: section <rdkafka_options> is not used in <store> of rdkafka2 plugin
```

**Environment details**:
- Kubernetes version - v1.30.9+rke2r1
- Cloud-provider/provisioner - on-premise
- logging-operator version - 5.2.0
- Install method - helm

/kind bug
