### ISSUE TITLE
Typo in the q_out_size attribute of the disk_buffer parameter in SyslogNGClusterOutput/SyslogNGOutput

### ISSUE THREAD

**Issue by verdel** [kube-logging/logging-operator#2021]
**Describe the bug**:
An error was made in the attribute name `q_out_size` of the `disk_buffer` parameter in `SyslogNGClusterOutput`/`SyslogNGOutput`. The attribute name is carried over to the final AxoSyslog configuration as-is.

In AxoSyslog version 4.7.1, used in logging operator version 5.2.0, the attribute is called [qout_size](https://github.com/axoflow/axosyslog/blob/afd229d3ec2350fe171622755f11a63d3e8d6956/modules/diskq/diskq-parser.c#L42).

**Expected behaviour**:

The attribute should be named `qout_size` and passed to the syslog-ng configuration as is.

**Steps to reproduce the bug**:

1. Create custom resource `SyslogNGClusterOutput`

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGClusterOutput
metadata:
  name: loki-cluster-output
  namespace: cattle-logging-system
spec:
  loki:
    url: loki.loki.svc.cluster.local:9100
    auth:
      insecure: {}
    timestamp: "msg"
    batch-timeout: 10000
    disk_buffer:
      dir: /buffers
      disk_buf_size: 5368709120
      reliable: true
      compaction: true
      q_out_size: 10
```
2. View logs from `syslog-ng-syslog-ng-configcheck` pod

```
Setting current version as config version; version='4.7'
Error parsing disk_buffer, syntax error, unexpected LL_IDENTIFIER, expecting ')' in /etc/syslog-ng/config/syslog-ng.conf:20:124-20:134:
15
16      destination "clusteroutput_cattle-logging-system_loki-cluster-output" {
17          loki(auth(insecure()) labels(
18              "cluster" => "internal"
19              "type" => "vault-audit-log"
20---->     ) url("loki.loki.svc.cluster.local:9100") disk_buffer(disk_buf_size(5368709120) reliable(yes) compaction(yes) dir("/buffers") q_out_size(10)) batch-timeout(10000) persist_name("clusteroutput_cattle-logging-system_loki-cluster-output") timestamp("msg"));
20---->                                                                                                                            ^^^^^^^^^^
21      };
22
23      log {
24          source("main_input");
25          log {
```

**Environment details**:
- Kubernetes version - v1.30.9+rke2r1
- Cloud-provider/provisioner - on-premise
- logging-operator version - 5.2.0
- Install method - helm

/kind bug
