### ISSUE TITLE
EnhanceK8s filter in globalFilters section of the Logging spec doesn't work in version 5.3

### ISSUE THREAD

**Issue by mohd-aslam** [kube-logging/logging-operator#2045]
EnhanceK8s filter doesn't work in the Logging spec doesn't work in version 5.3. However its showing in the documentation.

https://kube-logging.dev/docs/examples/sumologic/

**Error**
```
config resource: .spec.globalFilters[0].enhanceK8s: field not declared in schema
```

**Logging configuration:**

```
# Source: logging-operator/charts/logging-operator/templates/logging/logging.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-operator
  labels:
    app.kubernetes.io/name: logging-operator
    helm.sh/chart: logging-operator-5.3.0
    app.kubernetes.io/instance: logging-operator
    app.kubernetes.io/version: "5.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  skipInvalidResources: true
  fluentd:
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
    bufferVolumeMetrics:
      serviceMonitor: true
    metrics:
      interval: 10s
      path: /metrics
      serviceMonitor: true
    podPriorityClassName: system-node-critical
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 1
        memory: 1Gi
    scaling:
      replicas: 2
  globalFilters:
  - enhanceK8s: {}
  clusterDomain: cluster.local.
  controlNamespace: kube-system
  enableRecreateWorkloadOnImmutableFieldChange: true
```

**K8S version:** v1.28.15+rke2r1

Issue: We want to upgrade our current logging-operator from 4.3 to 5.3 (latest). We use different outputs and SumoLogic is one of them. SumoLogic output has been removed from current logging-operator.
