### ISSUE TITLE
Concat filter : `multiline_end_regexp` value is not formatted properly in Fluentd config

### ISSUE THREAD

**Issue by loic-brtd** [kube-logging/logging-operator#2071]
**Describe the bug**:
When using the [Concat Filter](https://kube-logging.dev/docs/configuration/plugins/filters/concat/), I think the regexp value for the field `multiline_end_regexp` is not properly formatted into the generated Fluentd config : 

My Flow configuration:
```yaml
apiVersion: v1
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Flow
  metadata:
    name: my-flow
    namespace: xxx
  spec:
    filters:
    - concat:
        key: log
        multiline_end_regexp: /\n$/
        separator: ""
        use_first_timestamp: true
    - grep:
        regexp:
        - key: log
          pattern: /^\{.*\}/
    - parser:
        key_name: log
        parse:
          type: json
        remove_key_name_field: true
        reserve_data: true
    localOutputRefs:
    - my-output
    match:
    - select:
        container_names:
        - xxx
```
The resulting FluentdConfig (taken from the logs of the pod `rancher-logging-root-fluentd-configcheck`) has the value `"/\\n$/"` for the `multiline_end_regexp` field : 
```html
  <label @2b0669f6af9ddff877bae45460fe9d59>
    <filter **>
      @type concat
      @id flow:xxx:my-flow:0
      key "log"
      multiline_end_regexp "/\\n$/"
      use_first_timestamp true
    </filter>
    <filter **>
      @type grep
      @id flow:xxx:my-flow:1
      <regexp>
        key "log"
        pattern /^\{.*\}/
      </regexp>
    </filter>
    <filter **>
      @type parser
      @id flow:xxx:my-flow:2
      key_name "log"
      remove_key_name_field true
      reserve_data true
      <parse>
        @type "json"
      </parse>
    </filter>
    <match **>
      @type elasticsearch_data_stream
```

**Expected behaviour**:
I expect to obtain the value `/\n$/` in the Fluentd config : 
```html
    <filter **>
      @type concat
      @id flow:xxx:my-flow:0
      key "log"
      multiline_end_regexp /\n$/
      use_first_timestamp true
    </filter>
```

**Steps to reproduce the bug**:
- Create a flow with the above Flow configuration
- Check the generated Fluentd configuration

**Additional context**:
I'm dealing with JSON logs which have a size greater than 16 Kib an Docker splits them in multiples logs. I was trying to solve this problem by adding [this Fluentd configuration](https://github.com/bitnami/charts/issues/6272#issuecomment-879038778) but when porting it to my `Flow` resource, the regexp for the field `multiline_end_regexp` is not formatted properly in the resulting Fluentd config.

**Environment details**:
- Kubernetes version: v1.25.14
- Cloud-provider/provisioner: RKE1
- logging-operator version: 3.17.10
- Install method (e.g. helm or static manifests): Rancher Logging plugin (chart is `rancher-logging:102.0.3+up3.17.10`)
- Logs from the misbehaving component (and any other relevant logs): /
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: _see above_

/kind bug

**Comment by rowa78** [comment]
Hi, 

I have the exactly same problem. I have splitted logs and want to concat these lines with this concat-plugin. I am also not able to bring `"/\n$/"` to the generated fluentd-config. I also always get `'/\\n$'`.

But i found another solution. At least on my rke2 clusters, the log-format is:

```
2025-07-01T05:27:01.016227378+02:00 stdout P {"timestamp":"2025-07-01T03:26:20+00:00","level" .............
2025-07-01T05:27:01.01628641+02:00 stdout F foo bar .........
```

so the format is:

```
<timestamp> <stream> <tag> <content>

P = Partial - Log message is incomplete, more parts follow
F = Full - Log message is complete OR final part of multi-part message
```

Then i use the concat like this:

```
  filters:
    - concat:
        key: "message"           # log content
        partial_key: "logtag"    # P/F Flag
        partial_value: "P"       # concat if "P"
        separator: ""
        flush_interval: 5
    - parser:
        key_name: message
        reserve_data: true
        remove_key_name_field: false  
        emit_invalid_record_to_error: false
        parse:
          type: json
```

i think, using this logtag seems more stable than the linebreak-thing.

So my jsons get properly parsed, even if they are splitted over 2 lines. 

Regards,
Ronny
