### ISSUE TITLE
Operator not always picking all the logs from head of file

### ISSUE THREAD

**Issue by izaac** [kube-logging/logging-operator#582]
**Describe the bug**:
We've noticed that some of the logs are not reaching the backend in this case Elasticsearch. After some investigation the team noticed some of the logs were not leaving fluentbit.

**Expected behaviour**:
All the logs collected from local files should reach Elasticsearch (or any other log aggregation backend).

**Steps to reproduce the bug**:
- Single node k8s cluster (all roles) to simplify the analysis.
- In the cluster node run a sample sequential log generator
  - `sudo curl -L https://raw.githubusercontent.com/paynejacob/sequential-log-generator/master/example.sh | sh`
- save the sample yaml below as **head.yml**
- run the install script (requires kubectl and helm v3)
- once all the logging pods are up https://<elasticsearch_host>:7200/examplelogs/_search?pretty should return 3k+ log entries.

```shell
curl -XDELETE http://jpayne.do.rancher.space:7200/*
helm install rancher-logging-crd https://charts.rancher.io/assets/rancher-logging/rancher-logging-crd-3.6.000.tgz --create-namespace=true --namespace=cattle-logging-system
sleep 3
helm install --create-namespace=true --namespace=cattle-logging-system rancher-logging https://charts.rancher.io/assets/rancher-logging/rancher-logging-3.6.000.tgz
kubectl create namespace examplelogs
kubectl apply -f ~/head.yml
```

**Additional context**:
This is a Rancher packaged `logging-operator` but all upstream is untouched so we can expect to match functionality/features with v3.6 

**Environment details**:
- Kubernetes version: v1.18
- Cloud-provider/provisioner: Rancher provisioned RKE DigitalOcean cluster.
- logging-operator version: v3.6
- Install method: helm v3
- Logs from the misbehaving component: as provided in steps
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

**Sample yaml (head.yml)**

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: examplelogs
  namespace: examplelogs
spec:
  elasticsearch:
    host: <elasticsearch_host>
    port: 7200
    scheme: http
    ssl_verify: false
    ssl_version: TLSv1_2
    index_name: examplelogs
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: examplelogs
  namespace: examplelogs
spec:
  controlNamespace: cattle-logging-system
  fluentbit:
    inputTail:
      Tag: "examplelogs"
      Path: "/examplelogs/*.log"
    extraVolumeMounts:
      - source: "/examplelogs/"
        destination: "/examplelogs/"
        readOnly: true
  fluentd:
    disablePvc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: examplelogs
  namespace: examplelogs
spec:
  localOutputRefs:
    - examplelogs
  filters:
    - stdout:
        output_type: json
```

/kind bug
