### ISSUE TITLE
[Bug] splunk-hec output doesn't support chunk keys in buffer

### ISSUE THREAD

**Issue by dbason** [kube-logging/logging-operator#717]
**Describe the bug**:
When adding a buffer section to the splunkHec ClusterOutput it generates the following config:
```
<buffer tag,time>
```
This causes the config check to fail :
```
[error]: config error file="/fluentd/etc/generated.conf" error_class=Fluent::ConfigError error="this plugin 'Fluent::Plugin::SplunkHecOutput' cannot handle arguments for <buffer ...> section"
```

**Expected behaviour**:
Operator won't generate invalid config

**Steps to reproduce the bug**:
Use a ClusterOutput or Output with something like the following:
```
spec:
  splunkHec:
    buffer:
      flush_interval: 60s
      flush_mode: interval
      flush_thread_count: 16
      queued_chunks_limit_size: 300
      type: file
    hec_host: doesnotwork.com
    hec_token:
      valueFrom:
        secretKeyRef:
          key: user.password
          name: my-user
    index: test
    protocol: https
```

**Additional context**:
The splunk-hec doesn't currently support buffer chunk keys - https://github.com/splunk/fluent-plugin-splunk-hec/issues/150

**Environment details**:
- logging-operator version (e.g. 2.1.1): 3.9.0
- Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by kenankule** [comment]
It was possible for us to generate a valid config if we override the buffer tags parameter with an empty list
```
  splunkHec:
    buffer:
      type: file
      # Due to https://github.com/splunk/fluent-plugin-splunk-hec/issues/150
      # tags can't be used in the buffer section
      tags: "[]"
```
