### ISSUE TITLE
Fluentbit PSP doesn't contain allowed hostPath for /opt/logging-operator/<RELEASE_NAME/buffers

### ISSUE THREAD

**Issue by fplantinga-guida** [kube-logging/logging-operator#731]
**Describe the bug**:
I have deployed a Logging resource with the following fluentbit configuration:
```yaml
fluentbit:
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
    positiondb:
      hostPath:
        path: ""
    bufferStorageVolume:
      hostPath:
        path: ""
```
The daemonset is created but the pod creation fails with the following error:
```
Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4].hostPath.pathPrefix: Invalid value: "/opt/logging-operator/***/buffers": is not allowed to be used]**
```
When i check the PSP i only see an allowed hostPath for the positiondb volume. 
```
Spec:
  Allow Privilege Escalation:  false
  Allowed Host Paths:
    Path Prefix:  /var/lib/docker/containers
    Read Only:    true
    Path Prefix:  /var/log
    Read Only:    true
    Path Prefix:  /opt/logging-operator/***/positiondb
```

**Expected behaviour**:
A concise description of what you expected to happen.
When this Logging resource is created, an Allowed Host Path prefix for /buffers should be added to the PSP. 

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.
Deploy a Logging resource with the fluentbit configuration above. 

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): **v1.18.16-gke.502** 
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): **gke**
- logging-operator version (e.g. 2.1.1): **3.9.4**
- Install method (e.g. helm or static manifests): **helm**
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
