### ISSUE TITLE
Unable to match different label types in one Flow

### ISSUE THREAD

**Issue by niwza-ua** [kube-logging/logging-operator#746]
**Describe the bug**:
We are using different label types in our cluster.
```
kubernetes.label.app: foo
kubernetes.label.app.kubernetes.io/name: bar
```
Trying to match mixed type labels with one flow fails. The following flow definition results in no matched messages.
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  localOutputRefs:
    - es-output
  match:
    - select:
        labels:
          app: foo
          kubernetes.label.app.kubernetes.io/name: bar
```

**Expected behaviour**:
Messages should match regardless of label type.

**Steps to reproduce the bug**:
1. deploy two apps with different type labels to one namespace.
2. Try to match both labels in a flow with a label selector.

**Additional context**:
There are several issues reported around label type mismatch in EFK stack. 
https://github.com/elastic/beats/issues/12638
https://discuss.elastic.co/t/filebeats-auto-mapping-of-kubernetes-labels-causing-big-issues/154718

Possibly it is worth adding dedot filter for labels and anotations to fluentbit configuration and as well generate fluentd config using dedoted labels

**Environment details**:
- logging-operator version 3.9.5

/kind bug

**Comment by genofire** [comment]
if you mean an `OR` you need to create another  `select` block:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  localOutputRefs:
    - es-output
  match:
    - select:
        labels:
          app: foo
    - select:
        labels:
          kubernetes.label.app.kubernetes.io/name: bar
```


See documentation: https://kube-logging.github.io/docs/configuration/log-routing/#example-6-multiple-labels---or
