### ISSUE TITLE
Allow matching flows by namespace regex (or glob)

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#780]
**Is your feature request related to a problem? Please describe.**
I dont want to list all my namespaces in the include / exclude namespaces.

**Describe the solution you'd like**
I'd like to be able to match namespaces with a glob or regex in order to avoid repetition of tenants namespaces.

**Describe alternatives you've considered**
- Label all the pods with a matching annotation: Annoying in my case
- Select namespaces by labels: Not possible as of now (see https://github.com/banzaicloud/logging-operator/issues/496)

**Additional context**

Here's the desired syntax:
```yaml
  kind: ClusterFlow
  metadata:
    name: flow-sample
  spec:
    match:
      - exclude:
          namespaces:
            - 'project-*-monitoring'
            - 'project-*' 
            # or
            - 'project-([a-z-]+)-monitoring'
            - 'project-([a-z-]+)' 
```
