### ISSUE TITLE
Output ltsv delimiter

### ISSUE THREAD

**Issue by Negashev** [kube-logging/logging-operator#793]
**Is your feature request related to a problem? Please describe.**
delimiter does not use in format `ltsv` output
https://docs.fluentd.org/formatter/ltsv#delimiter
https://docs.fluentd.org/formatter/ltsv#label_delimiter
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: my-syslog
  namespace: ingress-nginx
spec:
  syslog:
    format:
      type: ltsv
      delimiter: '='        # <--- don't save CRD
      label_delimiter: ';'  # <--- don't save CRD
    host: my-syslog
    port: 601
    transport: tcp
```
**Describe the solution you'd like**
I want to change the default `delimiter` and `label_delimiter` in ltsv output

**Describe alternatives you've considered**
If you just take the standard fluentd installation
