### ISSUE TITLE
Elastic Index Lifecycle Management not working as expected

### ISSUE THREAD

**Issue by volleynator** [kube-logging/logging-operator#799]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
I want my indices to be rolled over regularly by using Elastic ILM policies. However, the ilm policy defined in my clusterOutput is not respected.

**Expected behaviour**:
ILM is created by logging-operator-logging

**Steps to reproduce the bug**:
These are the values of my logging-operator-logging helm chart:
```
# Reference name of the logging deployment
loggingRef: ""
# Disable configuration check before deploy
flowConfigCheckDisabled: false
# Use static configuration instead of generated config.
flowConfigOverride:	""

nameOverride: ""
fullnameOverride: ""

# If an immutable field is changed, delete the existing resource
# and recreate it with the new configuration.
enableRecreateWorkloadOnImmutableFieldChange: false

# Fluent-bit configurations https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluent-bit-spec
fluentbit:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

#Node agent Definition
nodeAgents: {}

# Fluentd configurations https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluentd-spec
fluentd:
  logLevel: debug
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 256Mi

  bufferStorageVolume:
    pvc:
      spec:
        resources:
          requests:
            storage: 10Gi

# Enable secure connection between fluentd and fluent-bit
tls:
  enabled: false
  # Shared key for fluentd authentication
  sharedKey: ""
  fluentbitSecretName: ""
  fluentdSecretName: ""

# Limit namespaces from where to read Flow and Output specs
watchNamespaces: []
# Control namespace that contains ClusterOutput and ClusterFlow resources
controlNamespace: ""

# defaultFlow
defaultFlow: {}

# defaultFlow
globalFilters: []

# ClusterOutputs to deploy
clusterOutputs:
  - name: es-output
    spec:
      elasticsearch:
        host: elasticsearch-master.logging.svc.cluster.local
        port: 9200
        scheme: http
        ssl_verify: false
        ssl_version: TLSv1_2
        buffer:
          timekey: 1m
          timekey_wait: 30s
          timekey_use_utc: true
        index_name: "e7-logs"
        include_timestamp: true
        logstash_format: false
        application_name: e7
        index_date_pattern: "now/w{xxxx.ww}"
        enable_ilm: true
        rollover_index: true
        ilm_policy_id: "fluentd-policy"
        ilm_policy: '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_size":"4gb","max_age":"7d","max_primary_shard_size":"2gb"}}},"cold":{"min_age":"7d","actions":{"set_priority":{"priority":0}}},"delete":{"min_age":"30d","actions":{"delete":{}}}}}}'
        # template_name: "e7-logs-template"
        data_stream_enable: true
        data_stream_name: "e7-stream"

clusterFlows:
  - name: es-output
    spec:
      filters:
       - dedot:
           de_dot_separator: "-"
           de_dot_nested: true
      globalOutputRefs:
        - es-output
```

**Additional context**:
Elastic Index Management tells me there is a stream defined and a ilm policy, however, the policy is not equals the defined policy inside my values.yaml

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): DigitalOcean
- logging-operator version (e.g. 2.1.1): 3.12.0
- logging-operator-logging version (e.g. 2.1.1): 3.9.5
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
