### ISSUE TITLE
FluentDConfigCheck does not get scheduled du to inherited anti-affinity rules

### ISSUE THREAD

**Issue by timbrd** [kube-logging/logging-operator#814]
I have added the following pod affinity rules to my fluentd config to ensure that the pods are spread over the nodes:

```
    fluentd:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                    - fluentd
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                    - fluentd
            topologyKey: "kubernetes.io/hostname"
```

Now the fluentd-configcheck pods stay in pending state. It seems that they inherit the configuraton of the fluentd statefulsets.

```
18m         Warning   FailedScheduling    pod/logging-operator-fluentd-configcheck-e97a6f8f     0/8 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) didn't match pod affinity/anti-affinity rules, 3 node(s) didn't match pod anti-affinity rules, 3 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.
```

Is there a way to make sure that the fluentd pods are distributed, but the configcheck pods are still scheduled?
