### ISSUE TITLE
replace geoip_2_database  by geoip2_database  into Flow and ClusterFlow CRD

### ISSUE THREAD

**Issue by konvergence** [kube-logging/logging-operator#896]
**Describe the bug**:
If I use the geoip_2_database parameter on a specifc path, the filter is rejected by fluentd

* But if I try the parameter geoip2_database  under the Flow or ClusterFlow, the paramter is ignored

**Expected behaviour**:
Normally the geoip filter need the parameter geoip2_database   not geoip_2_database  
Please update the CRD to replace geoip_2_database  by geoip2_database  

**Steps to reproduce the bug**:
* use PVC to generate a volume for /buffers
* download a maxmind database
* try to define the parameter geoip_2_database   or geoip2_database  

**Environment details**:
* Kubernetes version v1.20.10
* Cloud-provider/provisioner RKE1
* logging-operator version 3.16.0
* Install method helm
* Logs from the misbehaving component (and any other relevant logs):
```
2021-12-26 22:38:29 +0000 [warn]: parameter 'geoip_2_database' in <filter **>
  @type geoip
  @id clusterflow:logging:logging-flow-shuttle-audit:4
  backend_library geoip2_c
  geoip_2_database /buffers/maxmind/GeoLite2-City_20211221/GeoLite2-City.mmdb
  geoip_lookup_keys remote
  skip_adding_null_record true
  <record>
    city ${city.names.en["remote"]}
    country ${country.iso_code["remote"]}
    country_name ${country.names.en["remote"]}
    location { "lat" : ${location.latitude["remote"]}, "lon" : ${location.longitude["remote"]} }
  </record>
</filter> is not used.
```

* Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: logging-flow-shuttle-audit
  namespace: logging
spec:
  filters:
  - dedot:
      de_dot_nested: true
      de_dot_separator: '-'
  - record_modifier:
      records:
      - log: ${record['log'].gsub(/\"/,'').gsub(/\n/,'')}
  - parser:
      parse:
        delimiter: ;
        keys: THREAD,SESSION,IP,USER,LANG,ORIGIN,START_DATE,END_DATE,STATUS,ERROR,CALL,REPO,PROJECT,TARGET,PARAMS,DURATION
        null_empty_string: true
        type: tsv
      remove_key_name_field: false
      reserve_data: true
  - record_modifier:
      records:
      - DURATION_S: ${require 'time'; Time.parse(record['END_DATE']).to_i  - Time.parse(record['START_DATE']).to_i}
      - cluster: demo
      - tag: ${'kubernetes.var.log.containers.' + record['kubernetes']['namespace_name']  +
          '_' + record['kubernetes']['pod_name'] + '_'  + record['kubernetes']['container_name']}
      - log_type: k8s_normal_container
      - time: ${record['START_DATE']}
      - fingerprint: ${require 'base64'; require 'digest'; Base64::strict_encode64(Digest::MD5.digest(tag  +
          '_' + time.to_s + '_' + record['log']))}
      - remote: ${record['IP']}
  - geoip:
      backend_library: geoip2_c
      geoip_2_database: /buffers/maxmind/GeoLite2-City_20211221/GeoLite2-City.mmdb
      geoip_lookup_keys: remote
      records:
      - city: ${city.names.en["remote"]}
        country: ${country.iso_code["remote"]}
        country_name: ${country.names.en["remote"]}
        location: '''{ "lat" : ${location.latitude["remote"]}, "lon" : ${location.longitude["remote"]}
          }'''
  globalOutputRefs:
  - kafka-cluster-output
  match:
  - select:
      container_names:
      - stream-log-file-audit
      namespaces:
      - shuttle-foot-demo
```

/kind bug
