### ISSUE TITLE
logging-operator - error received after stop sequence was engaged

### ISSUE THREAD

**Issue by qdupuy** [kube-logging/logging-operator#921]
Hello,

I wanted to install the helm charts logging-operator on my kubernetes cluster, however I encounter the following problem :

```
{"level":"info","ts":1643188235.7183502,"msg":"Waited for 1.037446427s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/longhorn.io/v1beta1?timeout=32s\n"}
{"level":"error","ts":1643188235.7236505,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"EventTailer.logging-extensions.banzaicloud.io","error":"no matches for kind \"EventTailer\" in version \"logging-extensions.banzaicloud.io/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/source/source.go:127"}
{"level":"error","ts":1643188235.7239068,"logger":"controller-runtime.manager.controller.eventtailer","msg":"Could not wait for Cache to sync","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"EventTailer","error":"failed to wait for eventtailer caches to sync: no matches for kind \"EventTailer\" in version \"logging-extensions.banzaicloud.io/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/manager/internal.go:696"}
{"level":"error","ts":1643188235.7243013,"logger":"controller-runtime.manager.controller.hosttailer","msg":"Could not wait for Cache to sync","reconciler group":"logging-extensions.banzaicloud.io","reconciler kind":"HostTailer","error":"failed to wait for hosttailer caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/manager/internal.go:696"}
{"level":"error","ts":1643188235.7242916,"logger":"controller-runtime.manager.controller.logging","msg":"Could not wait for Cache to sync","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","error":"failed to wait for logging caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/manager/internal.go:696"}
{"level":"error","ts":1643188235.724392,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"failed to wait for hosttailer caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1643188235.7244577,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"failed to wait for logging caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1643188235.7245076,"logger":"setup","msg":"problem running manager","error":"failed to wait for eventtailer caches to sync: no matches for kind \"EventTailer\" in version \"logging-extensions.banzaicloud.io/v1alpha1\"","stacktrace":"main.main\n\t/workspace/main.go:192\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
{"level":"error","ts":1643188235.72456,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"leader election lost"}
```

I installed the latest version of helm charts and here is my configuration file : 

```
replicaCount: 1
image:
  repository: ghcr.io/banzaicloud/logging-operator
  tag: 3.17.0
  pullPolicy: IfNotPresent
extraArgs:
  - -enable-leader-election=true
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

podLabels: {}
annotations: {}

createCustomResource: false
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  kubernetes.io/hostname: x
  
tolerations:
  - key: dedicated
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}

http:
  port: 8080
  service:
    type: ClusterIP
    clusterIP: None
    annotations: {}
    labels: {}
rbac:
  enabled: true
  psp:
    enabled: true
    annotations:
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
      seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
podSecurityContext: {}
securityContext: {}

priorityClassName: {}

monitoring:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    metricRelabelings: []
    relabelings: []
```

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.20.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): RKE
- logging-operator version (e.g. 2.1.1):  3.17.0
- Install method (e.g. helm or static manifests): helm

/kind bug
