### ISSUE TITLE
How can we forward logs to different ES index ?

### ISSUE THREAD

**Issue by anubhavkr** [kube-logging/logging-operator#944]
I have 2 applications running in my cluster. I want to forward the first application log to one ES index(fluentd) and the second application log to another index(haproxy). I created two clusterFlows and clusterOutputs like mentioned below, but I am getting logs on one index which i am mentioning in last. Please let me know how can I forward different type of logs to different ES index.

```
clusterOutputs:
  - name: es-output-applogs
    spec:
     elasticsearch:
       host: 112.25.2.127
       port: 9200
       suppress_type_name: true
       logstash_format: true
       logstash_prefix: fluentd
       buffer:
         timekey: 1m
         timekey_wait: 30s
         timekey_use_utc: true
```
```
clusterFlows:
  - name: applogs
    spec:
      filters:
        - parser:
            remove_key_name_field: true
            reserve_time: true
            reserve_data: true
            parse:
              type: regexp 
              expression: /^\[(?<log_time>[^\]]*)\] \[(?<level>[^\]]*)\] \[(?<severity>[^\]]*)\] \[(?<module>[^\]]*)\] \[(?<deviceKey>[^\]]*)\] \[(?<reqID>[^\]]*)\] \[(?<httpfwd>[^\]]*)\] \[(?<httpResponse>[^\]]*)\] (?<message>.*)$/              
        - record_modifier:
            records:
              - cluster: "cluster-A"              
      match:
       - select:
           namespaces:
             - dev     
      globalOutputRefs:
        - es-output-applogs
```
```
clusterOutputs:
  - name: es-output-haproxy
    spec:
     elasticsearch:
       host: 112.25.2.127
       port: 9200
       suppress_type_name: true
       logstash_format: true
       logstash_prefix: haproxy
       buffer:
         timekey: 1m
         timekey_wait: 30s
         timekey_use_utc: true
```
```
clusterFlows:
  - name: haproxy
    spec:
      filters:
        - parser:
            remove_key_name_field: true
            reserve_data: true
            parse:
              type: regexp
              expression: /^\[*(?<time>[^\]]*) (?<process_name>\w+)\[(?<process_id>\d+)\]\W *(?<client_ip>[^ ]*)\W(?<client_port>\d+) \[(?<Time>.+)\] (?<f_end>[\w-]+) (?<b_end>[\D?\w-]+)\/(?<b_server>[\D?\w-]+) (?<tq>\D?\w+)\/(?<tw>\D?\w+)\/(?<tc>\D?\w+)\/(?<tr>\D?\w+)\/(?<tt>\D?\w+) (?<status_code>\D?\w+) (?<bytes>\d+) (?<captured_request_cookie>\S+) (?<captured_response_cookie>\S+) (?<termination_state>[\w-]+) (?<actconn>\d+)\/(?<feconn>\d+)\/(?<beconn>\d+)\/(?<srv_conn>\d+)\/(?<retries>\d+) (?<srv_queue>\d+)\/(?<backend_queue>\d+) \{*(?<source>[^\|]*)\|*(?<user_agent>[^\|]*)\)*\|(?<x-forwarder_ip>[^\}]*)\} \W*(?<api_method>[^ ]*) *(?<HTTP request>[^ ]*) *(?<HTTP version>[^ ]*)\W/
        - record_modifier:
            records:
              - cluster: "cluster-A"
      match:
       - select:
           namespaces:
             - dev
      globalOutputRefs:
        - es-output-haproxy
```

**Comment by Ancitik** [comment]
Hello @anubhavkr 

Use the index_name key in your (Cluster_)Output spec: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch/#elasticsearch-index_name

**Comment by anubhavkr** [comment]
Dear @Ancitik 

I used index_name in both clusterOutputs but still I am not getting logs in both the indexs. I want to send haproxy and applogs  logs on different indexs.

```
clusterOutputs:
  - name: haproxy
    spec:
     elasticsearch:
       host: 112.25.2.127
       port: 9200
       suppress_type_name: true
       logstash_format: true
       index_name: haproxy
       buffer:
         timekey: 1m
         timekey_wait: 30s
         timekey_use_utc: true
```
```
clusterOutputs:
  - name: applogs
    spec:
     elasticsearch:
       host: 112.25.2.127
       port: 9200
       suppress_type_name: true
       logstash_format: true       
       index_name: fluentd
       buffer:
         timekey: 1m
         timekey_wait: 30s
         timekey_use_utc: true  
```
