### ISSUE TITLE
Add ability to reference a directory and/or wildcard path in HostTailers

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#984]
**Is your feature request related to a problem? Please describe.**
I'm frustrated not being able to use HostTailer with file names i don't know by advance.

**Describe the solution you'd like**
Add ability to tail files referencing a directory or a wildcard path.

**Describe alternatives you've considered**
Use a self-made fluentbit configuration as rancher does it in https://github.com/rancher/charts/blob/release-v2.6.2/charts/rancher-logging/rancher-logging/100.0.0%2Bup3.12.0/templates/loggings/rke/configmap.yaml#L21

**Comment by ahma** [comment]
Hi, @aslafy-z could you please give us more details about your use case?  We've tried the hosttailer with wildcard  and this is works for us.

**Comment by karloramone** [comment]
How did you make it work? 

Here is my configuration that doesn't work:
```
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: kubelet
  namespace: infrastructure-logging
spec:
  fileTailers:
  - name: kubelet
    path: /var/lib/rancher/rke/log/kubelet*.log

```
and the file path is: 
`/var/lib/rancher/rke/log/kubelet_33eff5a64b09cf37ef3f4258907834079fe5fdb14a851f2589b232256638f521.log -> /var/lib/docker/containers/33eff5a64b09cf37ef3f4258907834079fe5fdb14a851f2589b232256638f521/33eff5a64b09cf37ef3f4258907834079fe5fdb14a851f2589b232256638f521-json.log`

**Comment by pepov** [comment]
Unfortunately we add the path to the command line of the sidecar container which I beleive works different then setting it in a config file, we need to look into this

**Comment by aslafy-z** [comment]
Tested with latest, it works with the following configuration:

```
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: sample
spec:
  fileTailers:
    - name: api
      path: /tmp/test/api_*.log
    - name: web
      path: /tmp/test/web_*.log
```

**Comment by PlayMTL** [comment]
Hey,

I tried to save the RKE logs via Hosttailer and developed the following workaround. The problem with the RKE logs is that they are only symlinks to the log files under /var/lib/docker/containers. But the path /var/lib/docker/containers is not mounted, because the defined path is "/var/lib/rancher/rke/log". Here it would be cool if you could simply define additional "mount paths" in the fileTailers without configuring the whole additional volume mount thing.

```
$ ll /var/lib/rancher/rke/log
kubelet_XXXXXXX.log -> /var/lib/docker/containers/XXXXXXX/XXXXXXX-json.log
```

```
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: rke-logs
spec:
  fileTailers:
    - containerOverrides:
        volumeMounts:
          - mountPath: /var/lib/docker/containers
            name: host-docker-path
            readOnly: true
          - mountPath: /var/pos
            name: positions
          - mountPath: /var/lib/rancher/rke/log
            name: var-lib-rancher-rke-log
      name: kublet
      path: /var/lib/rancher/rke/log/kubelet_*.log
  workloadOverrides:
    volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: Directory
        name: host-docker-path
      - hostPath:
          path: /var/pos
          type: ''
        name: positions
      - hostPath:
          path: /var/lib/rancher/rke/log
          type: ''
        name: var-lib-rancher-rke-log
```
